# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ClientWindow(object):
    def setupUi(self, ClientWindow):
        ClientWindow.setObjectName(_fromUtf8("ClientWindow"))
        ClientWindow.resize(763, 594)
        ClientWindow.setStyleSheet(_fromUtf8("color: rgb(6, 6, 6);"))
        self.centralwidget = QtGui.QWidget(ClientWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.ConfigurationPage = QtGui.QWidget()
        self.ConfigurationPage.setGeometry(QtCore.QRect(0, 0, 743, 452))
        self.ConfigurationPage.setAccessibleName(_fromUtf8(""))
        self.ConfigurationPage.setAutoFillBackground(True)
        self.ConfigurationPage.setObjectName(_fromUtf8("ConfigurationPage"))
        self.verticalLayoutWidget = QtGui.QWidget(self.ConfigurationPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 30, 663, 181))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radUDP = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radUDP.setChecked(True)
        self.radUDP.setObjectName(_fromUtf8("radUDP"))
        self.horizontalLayout.addWidget(self.radUDP, 0, QtCore.Qt.AlignHCenter)
        self.radTCP = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radTCP.setObjectName(_fromUtf8("radTCP"))
        self.horizontalLayout.addWidget(self.radTCP, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBox_2 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_3.addWidget(self.checkBox_2)
        self.checkBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.serverIPInput = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.serverIPInput.setInputMask(_fromUtf8(""))
        self.serverIPInput.setText(_fromUtf8(""))
        self.serverIPInput.setMaxLength(3333)
        self.serverIPInput.setObjectName(_fromUtf8("serverIPInput"))
        self.horizontalLayout_4.addWidget(self.serverIPInput)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.portaInput = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portaInput.sizePolicy().hasHeightForWidth())
        self.portaInput.setSizePolicy(sizePolicy)
        self.portaInput.setObjectName(_fromUtf8("portaInput"))
        self.horizontalLayout_4.addWidget(self.portaInput)
        self.pingButton = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pingButton.sizePolicy().hasHeightForWidth())
        self.pingButton.setSizePolicy(sizePolicy)
        self.pingButton.setObjectName(_fromUtf8("pingButton"))
        self.horizontalLayout_4.addWidget(self.pingButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.pingLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.pingLabel.setText(_fromUtf8(""))
        self.pingLabel.setObjectName(_fromUtf8("pingLabel"))
        self.verticalLayout_3.addWidget(self.pingLabel)
        self.verticalLayoutWidget.raise_()
        self.toolBox.addItem(self.ConfigurationPage, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 743, 452))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.layoutWidget = QtGui.QWidget(self.page_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 743, 451))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.applicationLOut = QtGui.QTextEdit(self.layoutWidget)
        self.applicationLOut.setObjectName(_fromUtf8("applicationLOut"))
        self.verticalLayout.addWidget(self.applicationLOut)
        self.transportLOut = QtGui.QTextEdit(self.layoutWidget)
        self.transportLOut.setObjectName(_fromUtf8("transportLOut"))
        self.verticalLayout.addWidget(self.transportLOut)
        self.internetLOut = QtGui.QTextEdit(self.layoutWidget)
        self.internetLOut.setObjectName(_fromUtf8("internetLOut"))
        self.verticalLayout.addWidget(self.internetLOut)
        self.physicalLOut = QtGui.QTextEdit(self.layoutWidget)
        self.physicalLOut.setObjectName(_fromUtf8("physicalLOut"))
        self.verticalLayout.addWidget(self.physicalLOut)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.clearButton = QtGui.QPushButton(self.layoutWidget)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.horizontalLayout_2.addWidget(self.clearButton)
        self.startButton = QtGui.QPushButton(self.layoutWidget)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout_2.addWidget(self.startButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.toolBox, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        ClientWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(ClientWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ClientWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(ClientWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        ClientWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtGui.QMenuBar(ClientWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 763, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        ClientWindow.setMenuBar(self.menubar)
        self.actionClient = QtGui.QAction(ClientWindow)
        self.actionClient.setObjectName(_fromUtf8("actionClient"))
        self.actionServer = QtGui.QAction(ClientWindow)
        self.actionServer.setObjectName(_fromUtf8("actionServer"))
        self.menuMenu.addAction(self.actionClient)
        self.menuMenu.addAction(self.actionServer)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(ClientWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ClientWindow)

    def retranslateUi(self, ClientWindow):
        ClientWindow.setWindowTitle(_translate("ClientWindow", "MainWindow", None))
        self.radUDP.setText(_translate("ClientWindow", "UDP", None))
        self.radTCP.setText(_translate("ClientWindow", "TCP", None))
        self.checkBox_2.setText(_translate("ClientWindow", "Simulação de colisão", None))
        self.checkBox.setText(_translate("ClientWindow", "Step-by-step", None))
        self.label.setText(_translate("ClientWindow", "Server IP:", None))
        self.label_2.setText(_translate("ClientWindow", "Porta:", None))
        self.pingButton.setText(_translate("ClientWindow", "Ping", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ConfigurationPage), _translate("ClientWindow", "Page 1", None))
        self.applicationLOut.setHtml(_translate("ClientWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.transportLOut.setHtml(_translate("ClientWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.clearButton.setText(_translate("ClientWindow", "Clear", None))
        self.startButton.setText(_translate("ClientWindow", "Start", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("ClientWindow", "Page 2", None))
        self.toolBar.setWindowTitle(_translate("ClientWindow", "toolBar", None))
        self.menuMenu.setTitle(_translate("ClientWindow", "Menu", None))
        self.actionClient.setText(_translate("ClientWindow", "Home", None))
        self.actionServer.setText(_translate("ClientWindow", "Configuration", None))

