# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newWindow.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NewMainWindow(object):
    def setupUi(self, NewMainWindow):
        NewMainWindow.setObjectName(_fromUtf8("NewMainWindow"))
        NewMainWindow.resize(780, 622)
        self.centralwidget = QtGui.QWidget(NewMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 0, 761, 561))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.mainPage = QtGui.QWidget()
        self.mainPage.setObjectName(_fromUtf8("mainPage"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.mainPage)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 711, 531))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(5, 50, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.serverButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverButton.sizePolicy().hasHeightForWidth())
        self.serverButton.setSizePolicy(sizePolicy)
        self.serverButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.serverButton.setStyleSheet(_fromUtf8("background-color: rgb(255,255, 255 );\n"
"selection-background-color: rgb(200, 200, 200);\n"
"font:  30pt \"Latin Modern Mono Caps\";"))
        self.serverButton.setObjectName(_fromUtf8("serverButton"))
        self.verticalLayout_3.addWidget(self.serverButton)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem2)
        self.clientButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.clientButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientButton.sizePolicy().hasHeightForWidth())
        self.clientButton.setSizePolicy(sizePolicy)
        self.clientButton.setMinimumSize(QtCore.QSize(85, 0))
        self.clientButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.clientButton.setToolTip(_fromUtf8(""))
        self.clientButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clientButton.setStyleSheet(_fromUtf8("background-color: rgb(255,255, 255 );\n"
"font:  30pt \"Latin Modern Mono Caps\";"))
        self.clientButton.setObjectName(_fromUtf8("clientButton"))
        self.verticalLayout_3.addWidget(self.clientButton)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem3)
        self.routerButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routerButton.sizePolicy().hasHeightForWidth())
        self.routerButton.setSizePolicy(sizePolicy)
        self.routerButton.setStyleSheet(_fromUtf8("background-color: rgb(255,255, 255 );\n"
"font:  30pt \"Latin Modern Mono Caps\";"))
        self.routerButton.setObjectName(_fromUtf8("routerButton"))
        self.verticalLayout_3.addWidget(self.routerButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem4 = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.horizontalLayoutWidget.raise_()
        self.stackedWidget.addWidget(self.mainPage)
        self.clientPage = QtGui.QWidget()
        self.clientPage.setObjectName(_fromUtf8("clientPage"))
        self.toolBox = QtGui.QToolBox(self.clientPage)
        self.toolBox.setGeometry(QtCore.QRect(0, 0, 741, 531))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.ConfigurationPage = QtGui.QWidget()
        self.ConfigurationPage.setGeometry(QtCore.QRect(0, 0, 741, 469))
        self.ConfigurationPage.setAccessibleName(_fromUtf8(""))
        self.ConfigurationPage.setAutoFillBackground(True)
        self.ConfigurationPage.setObjectName(_fromUtf8("ConfigurationPage"))
        self.verticalLayoutWidget = QtGui.QWidget(self.ConfigurationPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 30, 663, 261))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.line_3 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_4.addWidget(self.line_3)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.line = QtGui.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radUDP = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radUDP.setChecked(True)
        self.radUDP.setObjectName(_fromUtf8("radUDP"))
        self.horizontalLayout_2.addWidget(self.radUDP, 0, QtCore.Qt.AlignHCenter)
        self.radTCP = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radTCP.setObjectName(_fromUtf8("radTCP"))
        self.horizontalLayout_2.addWidget(self.radTCP, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.line_2 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_4.addWidget(self.line_2)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBox_2 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_3.addWidget(self.checkBox_2, 0, QtCore.Qt.AlignHCenter)
        self.checkBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_3.addWidget(self.checkBox, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.toolBox.addItem(self.ConfigurationPage, _fromUtf8(""))
        self.displayPage = QtGui.QWidget()
        self.displayPage.setGeometry(QtCore.QRect(0, 0, 741, 469))
        self.displayPage.setObjectName(_fromUtf8("displayPage"))
        self.layoutWidget_2 = QtGui.QWidget(self.displayPage)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 10, 743, 517))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.layoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.serverIPInput = QtGui.QLineEdit(self.layoutWidget_2)
        self.serverIPInput.setInputMask(_fromUtf8(""))
        self.serverIPInput.setText(_fromUtf8(""))
        self.serverIPInput.setMaxLength(3333)
        self.serverIPInput.setObjectName(_fromUtf8("serverIPInput"))
        self.horizontalLayout_4.addWidget(self.serverIPInput)
        self.label_2 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.portaInput = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portaInput.sizePolicy().hasHeightForWidth())
        self.portaInput.setSizePolicy(sizePolicy)
        self.portaInput.setObjectName(_fromUtf8("portaInput"))
        self.horizontalLayout_4.addWidget(self.portaInput)
        self.pingButton = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pingButton.sizePolicy().hasHeightForWidth())
        self.pingButton.setSizePolicy(sizePolicy)
        self.pingButton.setObjectName(_fromUtf8("pingButton"))
        self.horizontalLayout_4.addWidget(self.pingButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.clearButton = QtGui.QPushButton(self.layoutWidget_2)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.horizontalLayout_5.addWidget(self.clearButton)
        self.startButton = QtGui.QPushButton(self.layoutWidget_2)
        self.startButton.setCheckable(False)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout_5.addWidget(self.startButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_6 = QtGui.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.applicationLOut = QtGui.QTextEdit(self.layoutWidget_2)
        self.applicationLOut.setDocumentTitle(_fromUtf8(""))
        self.applicationLOut.setReadOnly(True)
        self.applicationLOut.setObjectName(_fromUtf8("applicationLOut"))
        self.verticalLayout.addWidget(self.applicationLOut)
        self.label_7 = QtGui.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.transportLOut = QtGui.QTextEdit(self.layoutWidget_2)
        self.transportLOut.setReadOnly(True)
        self.transportLOut.setObjectName(_fromUtf8("transportLOut"))
        self.verticalLayout.addWidget(self.transportLOut)
        self.label_8 = QtGui.QLabel(self.layoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.networkLOut = QtGui.QTextEdit(self.layoutWidget_2)
        self.networkLOut.setReadOnly(True)
        self.networkLOut.setObjectName(_fromUtf8("networkLOut"))
        self.verticalLayout.addWidget(self.networkLOut)
        self.label_9 = QtGui.QLabel(self.layoutWidget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.physicalLOut = QtGui.QTextEdit(self.layoutWidget_2)
        self.physicalLOut.setReadOnly(True)
        self.physicalLOut.setObjectName(_fromUtf8("physicalLOut"))
        self.verticalLayout.addWidget(self.physicalLOut)
        self.toolBox.addItem(self.displayPage, _fromUtf8(""))
        self.stackedWidget.addWidget(self.clientPage)
        NewMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(NewMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        NewMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(NewMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        NewMainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(NewMainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        NewMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(NewMainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(NewMainWindow)

    def retranslateUi(self, NewMainWindow):
        NewMainWindow.setWindowTitle(_translate("NewMainWindow", "MainWindow", None))
        self.serverButton.setText(_translate("NewMainWindow", "Server", None))
        self.clientButton.setText(_translate("NewMainWindow", "Client", None))
        self.routerButton.setText(_translate("NewMainWindow", "Router", None))
        self.label_3.setText(_translate("NewMainWindow", "Server configuration:", None))
        self.label_4.setText(_translate("NewMainWindow", "Transport Protocol:", None))
        self.radUDP.setText(_translate("NewMainWindow", "UDP", None))
        self.radTCP.setText(_translate("NewMainWindow", "TCP", None))
        self.label_5.setText(_translate("NewMainWindow", "Options:", None))
        self.checkBox_2.setText(_translate("NewMainWindow", "Simulação de colisão", None))
        self.checkBox.setText(_translate("NewMainWindow", "Step-by-step", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ConfigurationPage), _translate("NewMainWindow", "Configuration", None))
        self.label.setText(_translate("NewMainWindow", "Server IP:", None))
        self.label_2.setText(_translate("NewMainWindow", "Porta:", None))
        self.pingButton.setText(_translate("NewMainWindow", "Ping", None))
        self.clearButton.setText(_translate("NewMainWindow", "Clear", None))
        self.startButton.setText(_translate("NewMainWindow", "Start", None))
        self.label_6.setText(_translate("NewMainWindow", "Application Layer", None))
        self.applicationLOut.setHtml(_translate("NewMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label_7.setText(_translate("NewMainWindow", "Transport Layer", None))
        self.transportLOut.setHtml(_translate("NewMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label_8.setText(_translate("NewMainWindow", "Network Layer", None))
        self.label_9.setText(_translate("NewMainWindow", "Physical Layer", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.displayPage), _translate("NewMainWindow", "Display output", None))
        self.toolBar.setWindowTitle(_translate("NewMainWindow", "toolBar", None))

