/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.2
 *
 * Copyright (c) 2016 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt4.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef _QtOpenGLAPI_H
#define _QtOpenGLAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Deprecated_5_0
#define SIP_FEATURE_PyQt_NoOpenGLES
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_SystemTrayIcon
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SizeGrip
#define SIP_FEATURE_PyQt_OpenSSL
#define SIP_FEATURE_Py_DateTime
#define SIP_FEATURE_PyQt_NoQtPrintRangeBug
#define SIP_FEATURE_PyQt_WhatsThis
#define SIP_FEATURE_PyQt_ToolTip
#define SIP_FEATURE_PyQt_StatusTip
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11
#define SIP_TIMELINE_Qt_4_8_7


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_QGLFramebufferObject__Attachment 0
#define sipName_QGLFramebufferObject__Attachment &sipStrings_QtOpenGL[0]
#define sipNameNr_OpenGL_ES_CommonLite_Version_1_1 33
#define sipName_OpenGL_ES_CommonLite_Version_1_1 &sipStrings_QtOpenGL[33]
#define sipNameNr_OpenGL_ES_CommonLite_Version_1_0 66
#define sipName_OpenGL_ES_CommonLite_Version_1_0 &sipStrings_QtOpenGL[66]
#define sipNameNr_QGLFormat__OpenGLContextProfile 99
#define sipName_QGLFormat__OpenGLContextProfile &sipStrings_QtOpenGL[99]
#define sipNameNr_QGLFormat__OpenGLVersionFlags 131
#define sipName_QGLFormat__OpenGLVersionFlags &sipStrings_QtOpenGL[131]
#define sipNameNr_setGeometryOutputVertexCount 161
#define sipName_setGeometryOutputVertexCount &sipStrings_QtOpenGL[161]
#define sipNameNr_PremultipliedAlphaBindOption 190
#define sipName_PremultipliedAlphaBindOption &sipStrings_QtOpenGL[190]
#define sipNameNr_OpenGL_ES_Common_Version_1_1 219
#define sipName_OpenGL_ES_Common_Version_1_1 &sipStrings_QtOpenGL[219]
#define sipNameNr_OpenGL_ES_Common_Version_1_0 248
#define sipName_OpenGL_ES_Common_Version_1_0 &sipStrings_QtOpenGL[248]
#define sipNameNr_QGLFormat__OpenGLVersionFlag 277
#define sipName_QGLFormat__OpenGLVersionFlag &sipStrings_QtOpenGL[277]
#define sipNameNr_PyQt4_QtCore_pyqtWrapperType 306
#define sipName_PyQt4_QtCore_pyqtWrapperType &sipStrings_QtOpenGL[306]
#define sipNameNr_hasOpenGLFramebufferObjects 335
#define sipName_hasOpenGLFramebufferObjects &sipStrings_QtOpenGL[335]
#define sipNameNr_QGLFramebufferObjectFormat 363
#define sipName_QGLFramebufferObjectFormat &sipStrings_QtOpenGL[363]
#define sipNameNr_geometryOutputVertexCount 390
#define sipName_geometryOutputVertexCount &sipStrings_QtOpenGL[390]
#define sipNameNr_releaseFromDynamicTexture 416
#define sipName_releaseFromDynamicTexture &sipStrings_QtOpenGL[416]
#define sipNameNr_LinearFilteringBindOption 442
#define sipName_LinearFilteringBindOption &sipStrings_QtOpenGL[442]
#define sipNameNr_QGLShader__ShaderTypeBit 468
#define sipName_QGLShader__ShaderTypeBit &sipStrings_QtOpenGL[468]
#define sipNameNr_setInternalTextureFormat 493
#define sipName_setInternalTextureFormat &sipStrings_QtOpenGL[493]
#define sipNameNr_hasOpenGLFramebufferBlit 518
#define sipName_hasOpenGLFramebufferBlit &sipStrings_QtOpenGL[518]
#define sipNameNr_generateFontDisplayLists 543
#define sipName_generateFontDisplayLists &sipStrings_QtOpenGL[543]
#define sipNameNr_hasOpenGLShaderPrograms 568
#define sipName_hasOpenGLShaderPrograms &sipStrings_QtOpenGL[568]
#define sipNameNr_addShaderFromSourceFile 592
#define sipName_addShaderFromSourceFile &sipStrings_QtOpenGL[592]
#define sipNameNr_addShaderFromSourceCode 616
#define sipName_addShaderFromSourceCode &sipStrings_QtOpenGL[616]
#define sipNameNr_QGLBuffer__UsagePattern 640
#define sipName_QGLBuffer__UsagePattern &sipStrings_QtOpenGL[640]
#define sipNameNr_QGLContext__BindOptions 664
#define sipName_QGLContext__BindOptions &sipStrings_QtOpenGL[664]
#define sipNameNr_overlayTransparentColor 688
#define sipName_overlayTransparentColor &sipStrings_QtOpenGL[688]
#define sipNameNr_setDefaultOverlayFormat 712
#define sipName_setDefaultOverlayFormat &sipStrings_QtOpenGL[712]
#define sipNameNr_setPreferredPaintEngine 736
#define sipName_setPreferredPaintEngine &sipStrings_QtOpenGL[736]
#define sipNameNr_generateDynamicTexture 760
#define sipName_generateDynamicTexture &sipStrings_QtOpenGL[760]
#define sipNameNr_QGLContext__BindOption 783
#define sipName_QGLContext__BindOption &sipStrings_QtOpenGL[783]
#define sipNameNr_windowActivationChange 806
#define sipName_windowActivationChange &sipStrings_QtOpenGL[806]
#define sipNameNr_setGeometryOutputType 829
#define sipName_setGeometryOutputType &sipStrings_QtOpenGL[829]
#define sipNameNr_disableAttributeArray 851
#define sipName_disableAttributeArray &sipStrings_QtOpenGL[851]
#define sipNameNr_bindAttributeLocation 873
#define sipName_bindAttributeLocation &sipStrings_QtOpenGL[873]
#define sipNameNr_QGLShader__ShaderType 895
#define sipName_QGLShader__ShaderType &sipStrings_QtOpenGL[895]
#define sipNameNr_internalTextureFormat 917
#define sipName_internalTextureFormat &sipStrings_QtOpenGL[917]
#define sipNameNr_OpenGL_ES_Version_2_0 939
#define sipName_OpenGL_ES_Version_2_0 &sipStrings_QtOpenGL[939]
#define sipNameNr_NoDeprecatedFunctions 961
#define sipName_NoDeprecatedFunctions &sipStrings_QtOpenGL[961]
#define sipNameNr_mouseDoubleClickEvent 983
#define sipName_mouseDoubleClickEvent &sipStrings_QtOpenGL[983]
#define sipNameNr_setGeometryInputType 1005
#define sipName_setGeometryInputType &sipStrings_QtOpenGL[1005]
#define sipNameNr_setUniformValueArray 1026
#define sipName_setUniformValueArray &sipStrings_QtOpenGL[1026]
#define sipNameNr_enableAttributeArray 1047
#define sipName_enableAttributeArray &sipStrings_QtOpenGL[1047]
#define sipNameNr_updateDynamicTexture 1068
#define sipName_updateDynamicTexture &sipStrings_QtOpenGL[1068]
#define sipNameNr_bindToDynamicTexture 1089
#define sipName_bindToDynamicTexture &sipStrings_QtOpenGL[1089]
#define sipNameNr_CombinedDepthStencil 1110
#define sipName_CombinedDepthStencil &sipStrings_QtOpenGL[1110]
#define sipNameNr_QGLFramebufferObject 1131
#define sipName_QGLFramebufferObject &sipStrings_QtOpenGL[1131]
#define sipNameNr_setTextureCacheLimit 1152
#define sipName_setTextureCacheLimit &sipStrings_QtOpenGL[1152]
#define sipNameNr_CompatibilityProfile 1173
#define sipName_CompatibilityProfile &sipStrings_QtOpenGL[1173]
#define sipNameNr_OpenGLContextProfile 110
#define sipName_OpenGLContextProfile &sipStrings_QtOpenGL[110]
#define sipNameNr_defaultOverlayFormat 1194
#define sipName_defaultOverlayFormat &sipStrings_QtOpenGL[1194]
#define sipNameNr_setStencilBufferSize 1215
#define sipName_setStencilBufferSize &sipStrings_QtOpenGL[1215]
#define sipNameNr_fontDisplayListBase 1236
#define sipName_fontDisplayListBase &sipStrings_QtOpenGL[1236]
#define sipNameNr_initializeOverlayGL 1256
#define sipName_initializeOverlayGL &sipStrings_QtOpenGL[1256]
#define sipNameNr_InvertedYBindOption 1276
#define sipName_InvertedYBindOption &sipStrings_QtOpenGL[1276]
#define sipNameNr_OpenGL_Version_None 1296
#define sipName_OpenGL_Version_None &sipStrings_QtOpenGL[1296]
#define sipNameNr_DeprecatedFunctions 963
#define sipName_DeprecatedFunctions &sipStrings_QtOpenGL[963]
#define sipNameNr_defaultButtonNumber 1316
#define sipName_defaultButtonNumber &sipStrings_QtOpenGL[1316]
#define sipNameNr_setAttributeBuffer 1336
#define sipName_setAttributeBuffer &sipStrings_QtOpenGL[1336]
#define sipNameNr_geometryOutputType 1355
#define sipName_geometryOutputType &sipStrings_QtOpenGL[1355]
#define sipNameNr_makeOverlayCurrent 1374
#define sipName_makeOverlayCurrent &sipStrings_QtOpenGL[1374]
#define sipNameNr_openGLVersionFlags 1393
#define sipName_openGLVersionFlags &sipStrings_QtOpenGL[1393]
#define sipNameNr_setGreenBufferSize 1412
#define sipName_setGreenBufferSize &sipStrings_QtOpenGL[1412]
#define sipNameNr_setDirectRendering 1431
#define sipName_setDirectRendering &sipStrings_QtOpenGL[1431]
#define sipNameNr_setAlphaBufferSize 1450
#define sipName_setAlphaBufferSize &sipStrings_QtOpenGL[1450]
#define sipNameNr_setAccumBufferSize 1469
#define sipName_setAccumBufferSize &sipStrings_QtOpenGL[1469]
#define sipNameNr_setDepthBufferSize 1488
#define sipName_setDepthBufferSize &sipStrings_QtOpenGL[1488]
#define sipNameNr_OpenGLVersionFlags 142
#define sipName_OpenGLVersionFlags &sipStrings_QtOpenGL[142]
#define sipNameNr_OpenGL_Version_4_0 1507
#define sipName_OpenGL_Version_4_0 &sipStrings_QtOpenGL[1507]
#define sipNameNr_OpenGL_Version_3_3 1526
#define sipName_OpenGL_Version_3_3 &sipStrings_QtOpenGL[1526]
#define sipNameNr_OpenGL_Version_3_2 1545
#define sipName_OpenGL_Version_3_2 &sipStrings_QtOpenGL[1545]
#define sipNameNr_OpenGL_Version_3_1 1564
#define sipName_OpenGL_Version_3_1 &sipStrings_QtOpenGL[1564]
#define sipNameNr_OpenGL_Version_3_0 1583
#define sipName_OpenGL_Version_3_0 &sipStrings_QtOpenGL[1583]
#define sipNameNr_OpenGL_Version_2_1 1602
#define sipName_OpenGL_Version_2_1 &sipStrings_QtOpenGL[1602]
#define sipNameNr_OpenGL_Version_2_0 1621
#define sipName_OpenGL_Version_2_0 &sipStrings_QtOpenGL[1621]
#define sipNameNr_OpenGL_Version_1_5 1640
#define sipName_OpenGL_Version_1_5 &sipStrings_QtOpenGL[1640]
#define sipNameNr_OpenGL_Version_1_4 1659
#define sipName_OpenGL_Version_1_4 &sipStrings_QtOpenGL[1659]
#define sipNameNr_OpenGL_Version_1_3 1678
#define sipName_OpenGL_Version_1_3 &sipStrings_QtOpenGL[1678]
#define sipNameNr_OpenGL_Version_1_2 1697
#define sipName_OpenGL_Version_1_2 &sipStrings_QtOpenGL[1697]
#define sipNameNr_OpenGL_Version_1_1 1716
#define sipName_OpenGL_Version_1_1 &sipStrings_QtOpenGL[1716]
#define sipNameNr_QGL__FormatOptions 1735
#define sipName_QGL__FormatOptions &sipStrings_QtOpenGL[1735]
#define sipNameNr_escapeButtonNumber 1754
#define sipName_escapeButtonNumber &sipStrings_QtOpenGL[1754]
#define sipNameNr_focusNextPrevChild 1773
#define sipName_focusNextPrevChild &sipStrings_QtOpenGL[1773]
#define sipNameNr_1792 1792
#define sipName_1792 &sipStrings_QtOpenGL[1792]
#define sipNameNr_geometryInputType 1810
#define sipName_geometryInputType &sipStrings_QtOpenGL[1810]
#define sipNameNr_setAttributeValue 1828
#define sipName_setAttributeValue &sipStrings_QtOpenGL[1828]
#define sipNameNr_setAttributeArray 1846
#define sipName_setAttributeArray &sipStrings_QtOpenGL[1846]
#define sipNameNr_attributeLocation 1864
#define sipName_attributeLocation &sipStrings_QtOpenGL[1864]
#define sipNameNr_compileSourceFile 1882
#define sipName_compileSourceFile &sipStrings_QtOpenGL[1882]
#define sipNameNr_compileSourceCode 1900
#define sipName_compileSourceCode &sipStrings_QtOpenGL[1900]
#define sipNameNr_hasOpenGLPbuffers 1918
#define sipName_hasOpenGLPbuffers &sipStrings_QtOpenGL[1918]
#define sipNameNr_PixelUnpackBuffer 1936
#define sipName_PixelUnpackBuffer &sipStrings_QtOpenGL[1936]
#define sipNameNr_QGLBuffer__Access 1954
#define sipName_QGLBuffer__Access &sipStrings_QtOpenGL[1954]
#define sipNameNr_setAutoBufferSwap 1972
#define sipName_setAutoBufferSwap &sipStrings_QtOpenGL[1972]
#define sipNameNr_convertToGLFormat 1990
#define sipName_convertToGLFormat &sipStrings_QtOpenGL[1990]
#define sipNameNr_DefaultBindOption 2008
#define sipName_DefaultBindOption &sipStrings_QtOpenGL[2008]
#define sipNameNr_textureCacheLimit 2026
#define sipName_textureCacheLimit &sipStrings_QtOpenGL[2026]
#define sipNameNr_setBlueBufferSize 2044
#define sipName_setBlueBufferSize &sipStrings_QtOpenGL[2044]
#define sipNameNr_hasOpenGLOverlays 2062
#define sipName_hasOpenGLOverlays &sipStrings_QtOpenGL[2062]
#define sipNameNr_stencilBufferSize 2080
#define sipName_stencilBufferSize &sipStrings_QtOpenGL[2080]
#define sipNameNr_OpenGLVersionFlag 288
#define sipName_OpenGLVersionFlag &sipStrings_QtOpenGL[288]
#define sipNameNr_IndirectRendering 2098
#define sipName_IndirectRendering &sipStrings_QtOpenGL[2098]
#define sipNameNr_QGL__FormatOption 2116
#define sipName_QGL__FormatOption &sipStrings_QtOpenGL[2116]
#define sipNameNr_mouseReleaseEvent 2134
#define sipName_mouseReleaseEvent &sipStrings_QtOpenGL[2134]
#define sipNameNr_sip_simplewrapper 2152
#define sipName_sip_simplewrapper &sipStrings_QtOpenGL[2152]
#define sipNameNr_removeAllShaders 2170
#define sipName_removeAllShaders &sipStrings_QtOpenGL[2170]
#define sipNameNr_QGLShaderProgram 2187
#define sipName_QGLShaderProgram &sipStrings_QtOpenGL[2187]
#define sipNameNr_hasOpenGLShaders 2204
#define sipName_hasOpenGLShaders &sipStrings_QtOpenGL[2204]
#define sipNameNr_setTextureTarget 2221
#define sipName_setTextureTarget &sipStrings_QtOpenGL[2221]
#define sipNameNr_deleteOldContext 2238
#define sipName_deleteOldContext &sipStrings_QtOpenGL[2238]
#define sipNameNr_MipmapBindOption 2255
#define sipName_MipmapBindOption &sipStrings_QtOpenGL[2255]
#define sipNameNr_setWindowCreated 2272
#define sipName_setWindowCreated &sipStrings_QtOpenGL[2272]
#define sipNameNr_setRedBufferSize 2289
#define sipName_setRedBufferSize &sipStrings_QtOpenGL[2289]
#define sipNameNr_setSampleBuffers 2306
#define sipName_setSampleBuffers &sipStrings_QtOpenGL[2306]
#define sipNameNr_setMouseTracking 2323
#define sipName_setMouseTracking &sipStrings_QtOpenGL[2323]
#define sipNameNr_contextMenuEvent 2340
#define sipName_contextMenuEvent &sipStrings_QtOpenGL[2340]
#define sipNameNr_inputMethodEvent 2357
#define sipName_inputMethodEvent &sipStrings_QtOpenGL[2357]
#define sipNameNr_inputMethodQuery 2374
#define sipName_inputMethodQuery &sipStrings_QtOpenGL[2374]
#define sipNameNr_setDefaultFormat 2391
#define sipName_setDefaultFormat &sipStrings_QtOpenGL[2391]
#define sipNameNr_disconnectNotify 2408
#define sipName_disconnectNotify &sipStrings_QtOpenGL[2408]
#define sipNameNr_setUniformValue 2425
#define sipName_setUniformValue &sipStrings_QtOpenGL[2425]
#define sipNameNr_uniformLocation 2441
#define sipName_uniformLocation &sipStrings_QtOpenGL[2441]
#define sipNameNr_blitFramebuffer 2457
#define sipName_blitFramebuffer &sipStrings_QtOpenGL[2457]
#define sipNameNr_setUsagePattern 2473
#define sipName_setUsagePattern &sipStrings_QtOpenGL[2473]
#define sipNameNr_PixelPackBuffer 2489
#define sipName_PixelPackBuffer &sipStrings_QtOpenGL[2489]
#define sipNameNr_QGLBuffer__Type 2505
#define sipName_QGLBuffer__Type &sipStrings_QtOpenGL[2505]
#define sipNameNr_resizeOverlayGL 2521
#define sipName_resizeOverlayGL &sipStrings_QtOpenGL[2521]
#define sipNameNr_updateOverlayGL 2537
#define sipName_updateOverlayGL &sipStrings_QtOpenGL[2537]
#define sipNameNr_grabFrameBuffer 2553
#define sipName_grabFrameBuffer &sipStrings_QtOpenGL[2553]
#define sipNameNr_requestedFormat 2569
#define sipName_requestedFormat &sipStrings_QtOpenGL[2569]
#define sipNameNr_setSwapInterval 2585
#define sipName_setSwapInterval &sipStrings_QtOpenGL[2585]
#define sipNameNr_greenBufferSize 2601
#define sipName_greenBufferSize &sipStrings_QtOpenGL[2601]
#define sipNameNr_directRendering 2100
#define sipName_directRendering &sipStrings_QtOpenGL[2100]
#define sipNameNr_setDoubleBuffer 2617
#define sipName_setDoubleBuffer &sipStrings_QtOpenGL[2617]
#define sipNameNr_alphaBufferSize 2633
#define sipName_alphaBufferSize &sipStrings_QtOpenGL[2633]
#define sipNameNr_accumBufferSize 2649
#define sipName_accumBufferSize &sipStrings_QtOpenGL[2649]
#define sipNameNr_depthBufferSize 2665
#define sipName_depthBufferSize &sipStrings_QtOpenGL[2665]
#define sipNameNr_NoSampleBuffers 2681
#define sipName_NoSampleBuffers &sipStrings_QtOpenGL[2681]
#define sipNameNr_NoStereoBuffers 2697
#define sipName_NoStereoBuffers &sipStrings_QtOpenGL[2697]
#define sipNameNr_NoStencilBuffer 2713
#define sipName_NoStencilBuffer &sipStrings_QtOpenGL[2713]
#define sipNameNr_DirectRendering 1434
#define sipName_DirectRendering &sipStrings_QtOpenGL[1434]
#define sipNameNr_aspectRatioMode 2729
#define sipName_aspectRatioMode &sipStrings_QtOpenGL[2729]
#define sipNameNr_deviceTransform 2745
#define sipName_deviceTransform &sipStrings_QtOpenGL[2745]
#define sipNameNr_minimumSizeHint 2761
#define sipName_minimumSizeHint &sipStrings_QtOpenGL[2761]
#define sipNameNr_mousePressEvent 2777
#define sipName_mousePressEvent &sipStrings_QtOpenGL[2777]
#define sipNameNr_keyReleaseEvent 2793
#define sipName_keyReleaseEvent &sipStrings_QtOpenGL[2793]
#define sipNameNr_QGLPixelBuffer 2809
#define sipName_QGLPixelBuffer &sipStrings_QtOpenGL[2809]
#define sipNameNr_internalFormat 2824
#define sipName_internalFormat &sipStrings_QtOpenGL[2824]
#define sipNameNr_autoBufferSwap 2839
#define sipName_autoBufferSwap &sipStrings_QtOpenGL[2839]
#define sipNameNr_paintOverlayGL 2854
#define sipName_paintOverlayGL &sipStrings_QtOpenGL[2854]
#define sipNameNr_overlayContext 2869
#define sipName_overlayContext &sipStrings_QtOpenGL[2869]
#define sipNameNr_setInitialized 2884
#define sipName_setInitialized &sipStrings_QtOpenGL[2884]
#define sipNameNr_deviceIsPixmap 2899
#define sipName_deviceIsPixmap &sipStrings_QtOpenGL[2899]
#define sipNameNr_currentContext 2914
#define sipName_currentContext &sipStrings_QtOpenGL[2914]
#define sipNameNr_getProcAddress 2929
#define sipName_getProcAddress &sipStrings_QtOpenGL[2929]
#define sipNameNr_blueBufferSize 2944
#define sipName_blueBufferSize &sipStrings_QtOpenGL[2944]
#define sipNameNr_NoAlphaChannel 2959
#define sipName_NoAlphaChannel &sipStrings_QtOpenGL[2959]
#define sipNameNr_languageChange 2974
#define sipName_languageChange &sipStrings_QtOpenGL[2974]
#define sipNameNr_selectedFilter 2989
#define sipName_selectedFilter &sipStrings_QtOpenGL[2989]
#define sipNameNr_heightForWidth 3004
#define sipName_heightForWidth &sipStrings_QtOpenGL[3004]
#define sipNameNr_dragLeaveEvent 3019
#define sipName_dragLeaveEvent &sipStrings_QtOpenGL[3019]
#define sipNameNr_dragEnterEvent 3034
#define sipName_dragEnterEvent &sipStrings_QtOpenGL[3034]
#define sipNameNr_mouseMoveEvent 3049
#define sipName_mouseMoveEvent &sipStrings_QtOpenGL[3049]
#define sipNameNr_PyQt4_QtOpenGL 3064
#define sipName_PyQt4_QtOpenGL &sipStrings_QtOpenGL[3064]
#define sipNameNr_ShaderTypeBit 479
#define sipName_ShaderTypeBit &sipStrings_QtOpenGL[479]
#define sipNameNr_setAttachment 3079
#define sipName_setAttachment &sipStrings_QtOpenGL[3079]
#define sipNameNr_qglClearColor 3093
#define sipName_qglClearColor &sipStrings_QtOpenGL[3093]
#define sipNameNr_windowCreated 3107
#define sipName_windowCreated &sipStrings_QtOpenGL[3107]
#define sipNameNr_chooseContext 3121
#define sipName_chooseContext &sipStrings_QtOpenGL[3121]
#define sipNameNr_deleteTexture 3135
#define sipName_deleteTexture &sipStrings_QtOpenGL[3135]
#define sipNameNr_textureTarget 3149
#define sipName_textureTarget &sipStrings_QtOpenGL[3149]
#define sipNameNr_redBufferSize 3163
#define sipName_redBufferSize &sipStrings_QtOpenGL[3163]
#define sipNameNr_sampleBuffers 3177
#define sipName_sampleBuffers &sipStrings_QtOpenGL[3177]
#define sipNameNr_FormatOptions 1740
#define sipName_FormatOptions &sipStrings_QtOpenGL[1740]
#define sipNameNr_NoAccumBuffer 3191
#define sipName_NoAccumBuffer &sipStrings_QtOpenGL[3191]
#define sipNameNr_NoDepthBuffer 3205
#define sipName_NoDepthBuffer &sipStrings_QtOpenGL[3205]
#define sipNameNr_SampleBuffers 2309
#define sipName_SampleBuffers &sipStrings_QtOpenGL[2309]
#define sipNameNr_StereoBuffers 2699
#define sipName_StereoBuffers &sipStrings_QtOpenGL[2699]
#define sipNameNr_StencilBuffer 2715
#define sipName_StencilBuffer &sipStrings_QtOpenGL[2715]
#define sipNameNr_paletteChange 3219
#define sipName_paletteChange &sipStrings_QtOpenGL[3219]
#define sipNameNr_enabledChange 3233
#define sipName_enabledChange &sipStrings_QtOpenGL[3233]
#define sipNameNr_transformMode 3247
#define sipName_transformMode &sipStrings_QtOpenGL[3247]
#define sipNameNr_dragMoveEvent 3261
#define sipName_dragMoveEvent &sipStrings_QtOpenGL[3261]
#define sipNameNr_focusOutEvent 3275
#define sipName_focusOutEvent &sipStrings_QtOpenGL[3275]
#define sipNameNr_keyPressEvent 3289
#define sipName_keyPressEvent &sipStrings_QtOpenGL[3289]
#define sipNameNr_defaultFormat 3303
#define sipName_defaultFormat &sipStrings_QtOpenGL[3303]
#define sipNameNr_connectNotify 2411
#define sipName_connectNotify &sipStrings_QtOpenGL[2411]
#define sipNameNr_removeShader 3317
#define sipName_removeShader &sipStrings_QtOpenGL[3317]
#define sipNameNr_NoAttachment 3330
#define sipName_NoAttachment &sipStrings_QtOpenGL[3330]
#define sipNameNr_usagePattern 3343
#define sipName_usagePattern &sipStrings_QtOpenGL[3343]
#define sipNameNr_UsagePattern 651
#define sipName_UsagePattern &sipStrings_QtOpenGL[651]
#define sipNameNr_VertexBuffer 3356
#define sipName_VertexBuffer &sipStrings_QtOpenGL[3356]
#define sipNameNr_initializeGL 3369
#define sipName_initializeGL &sipStrings_QtOpenGL[3369]
#define sipNameNr_renderPixmap 3382
#define sipName_renderPixmap &sipStrings_QtOpenGL[3382]
#define sipNameNr_NoBindOption 3395
#define sipName_NoBindOption &sipStrings_QtOpenGL[3395]
#define sipNameNr_chooseVisual 3408
#define sipName_chooseVisual &sipStrings_QtOpenGL[3408]
#define sipNameNr_shareContext 3421
#define sipName_shareContext &sipStrings_QtOpenGL[3421]
#define sipNameNr_minorVersion 3434
#define sipName_minorVersion &sipStrings_QtOpenGL[3434]
#define sipNameNr_majorVersion 3447
#define sipName_majorVersion &sipStrings_QtOpenGL[3447]
#define sipNameNr_swapInterval 3460
#define sipName_swapInterval &sipStrings_QtOpenGL[3460]
#define sipNameNr_doubleBuffer 3473
#define sipName_doubleBuffer &sipStrings_QtOpenGL[3473]
#define sipNameNr_SingleBuffer 3486
#define sipName_SingleBuffer &sipStrings_QtOpenGL[3486]
#define sipNameNr_AlphaChannel 2961
#define sipName_AlphaChannel &sipStrings_QtOpenGL[2961]
#define sipNameNr_DoubleBuffer 2620
#define sipName_DoubleBuffer &sipStrings_QtOpenGL[2620]
#define sipNameNr_FormatOption 2121
#define sipName_FormatOption &sipStrings_QtOpenGL[2121]
#define sipNameNr_sourceRegion 3499
#define sipName_sourceRegion &sipStrings_QtOpenGL[3499]
#define sipNameNr_targetOffset 3512
#define sipName_targetOffset &sipStrings_QtOpenGL[3512]
#define sipNameNr_boundingRect 3525
#define sipName_boundingRect &sipStrings_QtOpenGL[3525]
#define sipNameNr_midLineWidth 3538
#define sipName_midLineWidth &sipStrings_QtOpenGL[3538]
#define sipNameNr_focusInEvent 3551
#define sipName_focusInEvent &sipStrings_QtOpenGL[3551]
#define sipNameNr_findNearest 3564
#define sipName_findNearest &sipStrings_QtOpenGL[3564]
#define sipNameNr_QGLColormap 3576
#define sipName_QGLColormap &sipStrings_QtOpenGL[3576]
#define sipNameNr_DynamicCopy 3588
#define sipName_DynamicCopy &sipStrings_QtOpenGL[3588]
#define sipNameNr_DynamicRead 3600
#define sipName_DynamicRead &sipStrings_QtOpenGL[3600]
#define sipNameNr_DynamicDraw 3612
#define sipName_DynamicDraw &sipStrings_QtOpenGL[3612]
#define sipNameNr_IndexBuffer 3624
#define sipName_IndexBuffer &sipStrings_QtOpenGL[3624]
#define sipNameNr_setColormap 3636
#define sipName_setColormap &sipStrings_QtOpenGL[3636]
#define sipNameNr_shareWidget 3648
#define sipName_shareWidget &sipStrings_QtOpenGL[3648]
#define sipNameNr_BindOptions 676
#define sipName_BindOptions &sipStrings_QtOpenGL[676]
#define sipNameNr_initialized 3660
#define sipName_initialized &sipStrings_QtOpenGL[3660]
#define sipNameNr_drawTexture 3672
#define sipName_drawTexture &sipStrings_QtOpenGL[3672]
#define sipNameNr_bindTexture 3684
#define sipName_bindTexture &sipStrings_QtOpenGL[3684]
#define sipNameNr_swapBuffers 3696
#define sipName_swapBuffers &sipStrings_QtOpenGL[3696]
#define sipNameNr_doneCurrent 3708
#define sipName_doneCurrent &sipStrings_QtOpenGL[3708]
#define sipNameNr_makeCurrent 3720
#define sipName_makeCurrent &sipStrings_QtOpenGL[3720]
#define sipNameNr_CoreProfile 3732
#define sipName_CoreProfile &sipStrings_QtOpenGL[3732]
#define sipNameNr_AccumBuffer 3193
#define sipName_AccumBuffer &sipStrings_QtOpenGL[3193]
#define sipNameNr_DepthBuffer 3207
#define sipName_DepthBuffer &sipStrings_QtOpenGL[3207]
#define sipNameNr_tabletEvent 3744
#define sipName_tabletEvent &sipStrings_QtOpenGL[3744]
#define sipNameNr_button2Text 3756
#define sipName_button2Text &sipStrings_QtOpenGL[3756]
#define sipNameNr_button1Text 3768
#define sipName_button1Text &sipStrings_QtOpenGL[3768]
#define sipNameNr_actionEvent 3780
#define sipName_actionEvent &sipStrings_QtOpenGL[3780]
#define sipNameNr_paintEngine 3792
#define sipName_paintEngine &sipStrings_QtOpenGL[3792]
#define sipNameNr_resizeEvent 3804
#define sipName_resizeEvent &sipStrings_QtOpenGL[3804]
#define sipNameNr_changeEvent 3816
#define sipName_changeEvent &sipStrings_QtOpenGL[3816]
#define sipNameNr_customEvent 3828
#define sipName_customEvent &sipStrings_QtOpenGL[3828]
#define sipNameNr_eventFilter 3840
#define sipName_eventFilter &sipStrings_QtOpenGL[3840]
#define sipNameNr_isCompiled 3852
#define sipName_isCompiled &sipStrings_QtOpenGL[3852]
#define sipNameNr_sourceCode 3863
#define sipName_sourceCode &sipStrings_QtOpenGL[3863]
#define sipNameNr_shaderType 3874
#define sipName_shaderType &sipStrings_QtOpenGL[3874]
#define sipNameNr_ShaderType 906
#define sipName_ShaderType &sipStrings_QtOpenGL[906]
#define sipNameNr_attachment 3885
#define sipName_attachment &sipStrings_QtOpenGL[3885]
#define sipNameNr_Attachment 22
#define sipName_Attachment &sipStrings_QtOpenGL[22]
#define sipNameNr_entryColor 3896
#define sipName_entryColor &sipStrings_QtOpenGL[3896]
#define sipNameNr_setEntries 3907
#define sipName_setEntries &sipStrings_QtOpenGL[3907]
#define sipNameNr_StaticCopy 3918
#define sipName_StaticCopy &sipStrings_QtOpenGL[3918]
#define sipNameNr_StaticRead 3929
#define sipName_StaticRead &sipStrings_QtOpenGL[3929]
#define sipNameNr_StaticDraw 3940
#define sipName_StaticDraw &sipStrings_QtOpenGL[3940]
#define sipNameNr_StreamCopy 3951
#define sipName_StreamCopy &sipStrings_QtOpenGL[3951]
#define sipNameNr_StreamRead 3962
#define sipName_StreamRead &sipStrings_QtOpenGL[3962]
#define sipNameNr_StreamDraw 3973
#define sipName_StreamDraw &sipStrings_QtOpenGL[3973]
#define sipNameNr_renderText 3984
#define sipName_renderText &sipStrings_QtOpenGL[3984]
#define sipNameNr_useContext 3995
#define sipName_useContext &sipStrings_QtOpenGL[3995]
#define sipNameNr_BindOption 208
#define sipName_BindOption &sipStrings_QtOpenGL[208]
#define sipNameNr_areSharing 4006
#define sipName_areSharing &sipStrings_QtOpenGL[4006]
#define sipNameNr_QGLContext 4017
#define sipName_QGLContext &sipStrings_QtOpenGL[4017]
#define sipNameNr_setProfile 4028
#define sipName_setProfile &sipStrings_QtOpenGL[4028]
#define sipNameNr_hasOverlay 4039
#define sipName_hasOverlay &sipStrings_QtOpenGL[4039]
#define sipNameNr_setOverlay 4050
#define sipName_setOverlay &sipStrings_QtOpenGL[4050]
#define sipNameNr_setStencil 4061
#define sipName_setStencil &sipStrings_QtOpenGL[4061]
#define sipNameNr_setSamples 4072
#define sipName_setSamples &sipStrings_QtOpenGL[4072]
#define sipNameNr_ColorIndex 4083
#define sipName_ColorIndex &sipStrings_QtOpenGL[4083]
#define sipNameNr_HasOverlay 4094
#define sipName_HasOverlay &sipStrings_QtOpenGL[4094]
#define sipNameNr_fontChange 4105
#define sipName_fontChange &sipStrings_QtOpenGL[4105]
#define sipNameNr_setContext 4116
#define sipName_setContext &sipStrings_QtOpenGL[4116]
#define sipNameNr_enterEvent 4127
#define sipName_enterEvent &sipStrings_QtOpenGL[4127]
#define sipNameNr_leaveEvent 4138
#define sipName_leaveEvent &sipStrings_QtOpenGL[4138]
#define sipNameNr_testOption 4149
#define sipName_testOption &sipStrings_QtOpenGL[4149]
#define sipNameNr_setVisible 4160
#define sipName_setVisible &sipStrings_QtOpenGL[4160]
#define sipNameNr_closeEvent 4171
#define sipName_closeEvent &sipStrings_QtOpenGL[4171]
#define sipNameNr_wheelEvent 4182
#define sipName_wheelEvent &sipStrings_QtOpenGL[4182]
#define sipNameNr_paintEvent 4193
#define sipName_paintEvent &sipStrings_QtOpenGL[4193]
#define sipNameNr_fieldWidth 4204
#define sipName_fieldWidth &sipStrings_QtOpenGL[4204]
#define sipNameNr_childEvent 4215
#define sipName_childEvent &sipStrings_QtOpenGL[4215]
#define sipNameNr_timerEvent 4226
#define sipName_timerEvent &sipStrings_QtOpenGL[4226]
#define sipNameNr_setVersion 4237
#define sipName_setVersion &sipStrings_QtOpenGL[4237]
#define sipNameNr___invert__ 4248
#define sipName___invert__ &sipStrings_QtOpenGL[4248]
#define sipNameNr_programId 4259
#define sipName_programId &sipStrings_QtOpenGL[4259]
#define sipNameNr_addShader 4269
#define sipName_addShader &sipStrings_QtOpenGL[4269]
#define sipNameNr_QGLShader 4279
#define sipName_QGLShader &sipStrings_QtOpenGL[4279]
#define sipNameNr_setMipmap 4289
#define sipName_setMipmap &sipStrings_QtOpenGL[4289]
#define sipNameNr_setHandle 4299
#define sipName_setHandle &sipStrings_QtOpenGL[4299]
#define sipNameNr_isCreated 4309
#define sipName_isCreated &sipStrings_QtOpenGL[4309]
#define sipNameNr_QGLBuffer 4319
#define sipName_QGLBuffer &sipStrings_QtOpenGL[4319]
#define sipNameNr_withAlpha 4329
#define sipName_withAlpha &sipStrings_QtOpenGL[4329]
#define sipNameNr_QGLWidget 4339
#define sipName_QGLWidget &sipStrings_QtOpenGL[4339]
#define sipNameNr_isSharing 4349
#define sipName_isSharing &sipStrings_QtOpenGL[4349]
#define sipNameNr_NoProfile 4359
#define sipName_NoProfile &sipStrings_QtOpenGL[4359]
#define sipNameNr_hasOpenGL 4369
#define sipName_hasOpenGL &sipStrings_QtOpenGL[4369]
#define sipNameNr_setStereo 4379
#define sipName_setStereo &sipStrings_QtOpenGL[4379]
#define sipNameNr_QGLFormat 4389
#define sipName_QGLFormat &sipStrings_QtOpenGL[4389]
#define sipNameNr_NoOverlay 4399
#define sipName_NoOverlay &sipStrings_QtOpenGL[4399]
#define sipNameNr_operation 4409
#define sipName_operation &sipStrings_QtOpenGL[4409]
#define sipNameNr_setFormat 4419
#define sipName_setFormat &sipStrings_QtOpenGL[4419]
#define sipNameNr_moveEvent 4429
#define sipName_moveEvent &sipStrings_QtOpenGL[4429]
#define sipNameNr_lineWidth 4439
#define sipName_lineWidth &sipStrings_QtOpenGL[4439]
#define sipNameNr_setOption 4449
#define sipName_setOption &sipStrings_QtOpenGL[4449]
#define sipNameNr_showEvent 4459
#define sipName_showEvent &sipStrings_QtOpenGL[4459]
#define sipNameNr_hideEvent 4469
#define sipName_hideEvent &sipStrings_QtOpenGL[4469]
#define sipNameNr_dropEvent 4479
#define sipName_dropEvent &sipStrings_QtOpenGL[4479]
#define sipNameNr_directory 4489
#define sipName_directory &sipStrings_QtOpenGL[4489]
#define sipNameNr_alignment 4499
#define sipName_alignment &sipStrings_QtOpenGL[4499]
#define sipNameNr_ReadWrite 4509
#define sipName_ReadWrite &sipStrings_QtOpenGL[4509]
#define sipNameNr_WriteOnly 4519
#define sipName_WriteOnly &sipStrings_QtOpenGL[4519]
#define sipNameNr_precision 4529
#define sipName_precision &sipStrings_QtOpenGL[4529]
#define sipNameNr_isLinked 4539
#define sipName_isLinked &sipStrings_QtOpenGL[4539]
#define sipNameNr_shaderId 4548
#define sipName_shaderId &sipStrings_QtOpenGL[4548]
#define sipNameNr_Geometry 4557
#define sipName_Geometry &sipStrings_QtOpenGL[4557]
#define sipNameNr_Fragment 4566
#define sipName_Fragment &sipStrings_QtOpenGL[4566]
#define sipNameNr_entryRgb 4575
#define sipName_entryRgb &sipStrings_QtOpenGL[4575]
#define sipNameNr_setEntry 4584
#define sipName_setEntry &sipStrings_QtOpenGL[4584]
#define sipNameNr_allocate 4593
#define sipName_allocate &sipStrings_QtOpenGL[4593]
#define sipNameNr_bufferId 4602
#define sipName_bufferId &sipStrings_QtOpenGL[4602]
#define sipNameNr_resizeGL 4611
#define sipName_resizeGL &sipStrings_QtOpenGL[4611]
#define sipNameNr_updateGL 4620
#define sipName_updateGL &sipStrings_QtOpenGL[4620]
#define sipNameNr_qglColor 4629
#define sipName_qglColor &sipStrings_QtOpenGL[4629]
#define sipNameNr_listBase 4638
#define sipName_listBase &sipStrings_QtOpenGL[4638]
#define sipNameNr_setPlane 4647
#define sipName_setPlane &sipStrings_QtOpenGL[4647]
#define sipNameNr_setAccum 4656
#define sipName_setAccum &sipStrings_QtOpenGL[4656]
#define sipNameNr_setDepth 4665
#define sipName_setDepth &sipStrings_QtOpenGL[4665]
#define sipNameNr_fillRule 4674
#define sipName_fillRule &sipStrings_QtOpenGL[4674]
#define sipNameNr_tabArray 4683
#define sipName_tabArray &sipStrings_QtOpenGL[4683]
#define sipNameNr_tabStops 4692
#define sipName_tabStops &sipStrings_QtOpenGL[4692]
#define sipNameNr_userData 4701
#define sipName_userData &sipStrings_QtOpenGL[4701]
#define sipNameNr_setAlpha 4710
#define sipName_setAlpha &sipStrings_QtOpenGL[4710]
#define sipNameNr_colormap 4719
#define sipName_colormap &sipStrings_QtOpenGL[4719]
#define sipNameNr_sizeHint 4728
#define sipName_sizeHint &sipStrings_QtOpenGL[4728]
#define sipNameNr_shortcut 4737
#define sipName_shortcut &sipStrings_QtOpenGL[4737]
#define sipNameNr_behavior 4746
#define sipName_behavior &sipStrings_QtOpenGL[4746]
#define sipNameNr_position 4755
#define sipName_position &sipStrings_QtOpenGL[4755]
#define sipNameNr_fillChar 4764
#define sipName_fillChar &sipStrings_QtOpenGL[4764]
#define sipNameNr_ReadOnly 4773
#define sipName_ReadOnly &sipStrings_QtOpenGL[4773]
#define sipNameNr___bool__ 4782
#define sipName___bool__ &sipStrings_QtOpenGL[4782]
#define sipNameNr___ixor__ 4791
#define sipName___ixor__ &sipStrings_QtOpenGL[4791]
#define sipNameNr___iand__ 4800
#define sipName___iand__ &sipStrings_QtOpenGL[4800]
#define sipNameNr_shaders 4809
#define sipName_shaders &sipStrings_QtOpenGL[4809]
#define sipNameNr_buffers 1928
#define sipName_buffers &sipStrings_QtOpenGL[1928]
#define sipNameNr_isBound 4817
#define sipName_isBound &sipStrings_QtOpenGL[4817]
#define sipNameNr_paintGL 4825
#define sipName_paintGL &sipStrings_QtOpenGL[4825]
#define sipNameNr_profile 4833
#define sipName_profile &sipStrings_QtOpenGL[4833]
#define sipNameNr_stencil 4841
#define sipName_stencil &sipStrings_QtOpenGL[4841]
#define sipNameNr_samples 4849
#define sipName_samples &sipStrings_QtOpenGL[4849]
#define sipNameNr_destroy 4857
#define sipName_destroy &sipStrings_QtOpenGL[4857]
#define sipNameNr_exposed 4865
#define sipName_exposed &sipStrings_QtOpenGL[4865]
#define sipNameNr_toImage 4873
#define sipName_toImage &sipStrings_QtOpenGL[4873]
#define sipNameNr_button2 4881
#define sipName_button2 &sipStrings_QtOpenGL[4881]
#define sipNameNr_button1 4889
#define sipName_button1 &sipStrings_QtOpenGL[4889]
#define sipNameNr_quality 4897
#define sipName_quality &sipStrings_QtOpenGL[4897]
#define sipNameNr_devType 4905
#define sipName_devType &sipStrings_QtOpenGL[4905]
#define sipNameNr_yMargin 4913
#define sipName_yMargin &sipStrings_QtOpenGL[4913]
#define sipNameNr_xMargin 4921
#define sipName_xMargin &sipStrings_QtOpenGL[4921]
#define sipNameNr_caption 4929
#define sipName_caption &sipStrings_QtOpenGL[4929]
#define sipNameNr_texture 4937
#define sipName_texture &sipStrings_QtOpenGL[4937]
#define sipNameNr_setRgba 4945
#define sipName_setRgba &sipStrings_QtOpenGL[4945]
#define sipNameNr_release 4953
#define sipName_release &sipStrings_QtOpenGL[4953]
#define sipNameNr_options 4961
#define sipName_options &sipStrings_QtOpenGL[4961]
#define sipNameNr_context 4969
#define sipName_context &sipStrings_QtOpenGL[4969]
#define sipNameNr_isEmpty 4977
#define sipName_isEmpty &sipStrings_QtOpenGL[4977]
#define sipNameNr_isValid 4985
#define sipName_isValid &sipStrings_QtOpenGL[4985]
#define sipNameNr_filters 4993
#define sipName_filters &sipStrings_QtOpenGL[4993]
#define sipNameNr___xor__ 5001
#define sipName___xor__ &sipStrings_QtOpenGL[5001]
#define sipNameNr___ior__ 5009
#define sipName___ior__ &sipStrings_QtOpenGL[5009]
#define sipNameNr___and__ 5017
#define sipName___and__ &sipStrings_QtOpenGL[5017]
#define sipNameNr___int__ 5025
#define sipName___int__ &sipStrings_QtOpenGL[5025]
#define sipNameNr_stride 5033
#define sipName_stride &sipStrings_QtOpenGL[5033]
#define sipNameNr_Vertex 5040
#define sipName_Vertex &sipStrings_QtOpenGL[5040]
#define sipNameNr_mipmap 5047
#define sipName_mipmap &sipStrings_QtOpenGL[5047]
#define sipNameNr_glDraw 5054
#define sipName_glDraw &sipStrings_QtOpenGL[5054]
#define sipNameNr_glInit 5061
#define sipName_glInit &sipStrings_QtOpenGL[5061]
#define sipNameNr_stereo 5068
#define sipName_stereo &sipStrings_QtOpenGL[5068]
#define sipNameNr_yRound 5075
#define sipName_yRound &sipStrings_QtOpenGL[5075]
#define sipNameNr_xRound 5082
#define sipName_xRound &sipStrings_QtOpenGL[5082]
#define sipNameNr_metric 5089
#define sipName_metric &sipStrings_QtOpenGL[5089]
#define sipNameNr_layers 5096
#define sipName_layers &sipStrings_QtOpenGL[5096]
#define sipNameNr_sunken 5103
#define sipName_sunken &sipStrings_QtOpenGL[5103]
#define sipNameNr_option 5110
#define sipName_option &sipStrings_QtOpenGL[5110]
#define sipNameNr_height 5117
#define sipName_height &sipStrings_QtOpenGL[5117]
#define sipNameNr_proper 5124
#define sipName_proper &sipStrings_QtOpenGL[5124]
#define sipNameNr_value9 5131
#define sipName_value9 &sipStrings_QtOpenGL[5131]
#define sipNameNr_value8 5138
#define sipName_value8 &sipStrings_QtOpenGL[5138]
#define sipNameNr_value7 5145
#define sipName_value7 &sipStrings_QtOpenGL[5145]
#define sipNameNr_value6 5152
#define sipName_value6 &sipStrings_QtOpenGL[5152]
#define sipNameNr_value5 5159
#define sipName_value5 &sipStrings_QtOpenGL[5159]
#define sipNameNr_value4 5166
#define sipName_value4 &sipStrings_QtOpenGL[5166]
#define sipNameNr_value3 5173
#define sipName_value3 &sipStrings_QtOpenGL[5173]
#define sipNameNr_value2 5180
#define sipName_value2 &sipStrings_QtOpenGL[5180]
#define sipNameNr_value1 5187
#define sipName_value1 &sipStrings_QtOpenGL[5187]
#define sipNameNr_value0 5194
#define sipName_value0 &sipStrings_QtOpenGL[5194]
#define sipNameNr_Access 1965
#define sipName_Access &sipStrings_QtOpenGL[1965]
#define sipNameNr_symbol 5201
#define sipName_symbol &sipStrings_QtOpenGL[5201]
#define sipNameNr_suffix 5208
#define sipName_suffix &sipStrings_QtOpenGL[5208]
#define sipNameNr_prefix 5215
#define sipName_prefix &sipStrings_QtOpenGL[5215]
#define sipNameNr_device 5222
#define sipName_device &sipStrings_QtOpenGL[5222]
#define sipNameNr_format 5229
#define sipName_format &sipStrings_QtOpenGL[5229]
#define sipNameNr_detach 5236
#define sipName_detach &sipStrings_QtOpenGL[5236]
#define sipNameNr_target 5243
#define sipName_target &sipStrings_QtOpenGL[5243]
#define sipNameNr_action 5250
#define sipName_action &sipStrings_QtOpenGL[5250]
#define sipNameNr_column 5257
#define sipName_column &sipStrings_QtOpenGL[5257]
#define sipNameNr_create 5264
#define sipName_create &sipStrings_QtOpenGL[5264]
#define sipNameNr_handle 5271
#define sipName_handle &sipStrings_QtOpenGL[5271]
#define sipNameNr_filter 5278
#define sipName_filter &sipStrings_QtOpenGL[5278]
#define sipNameNr_parent 5285
#define sipName_parent &sipStrings_QtOpenGL[5285]
#define sipNameNr___ne__ 5292
#define sipName___ne__ &sipStrings_QtOpenGL[5292]
#define sipNameNr___eq__ 5299
#define sipName___eq__ &sipStrings_QtOpenGL[5299]
#define sipNameNr___or__ 5306
#define sipName___or__ &sipStrings_QtOpenGL[5306]
#define sipNameNr_Depth 4668
#define sipName_Depth &sipStrings_QtOpenGL[4668]
#define sipNameNr_accum 5313
#define sipName_accum &sipStrings_QtOpenGL[5313]
#define sipNameNr_plane 5319
#define sipName_plane &sipStrings_QtOpenGL[5319]
#define sipNameNr_depth 5325
#define sipName_depth &sipStrings_QtOpenGL[5325]
#define sipNameNr_brush 5331
#define sipName_brush &sipStrings_QtOpenGL[5331]
#define sipNameNr_alpha 5337
#define sipName_alpha &sipStrings_QtOpenGL[5337]
#define sipNameNr_hints 5343
#define sipName_hints &sipStrings_QtOpenGL[5343]
#define sipNameNr_width 5349
#define sipName_width &sipStrings_QtOpenGL[5349]
#define sipNameNr_reset 5355
#define sipName_reset &sipStrings_QtOpenGL[5355]
#define sipNameNr_unmap 5361
#define sipName_unmap &sipStrings_QtOpenGL[5361]
#define sipNameNr_write 5367
#define sipName_write &sipStrings_QtOpenGL[5367]
#define sipNameNr_flags 5373
#define sipName_flags &sipStrings_QtOpenGL[5373]
#define sipNameNr_event 5379
#define sipName_event &sipStrings_QtOpenGL[5379]
#define sipNameNr_msecs 5385
#define sipName_msecs &sipStrings_QtOpenGL[5385]
#define sipNameNr_state 5391
#define sipName_state &sipStrings_QtOpenGL[5391]
#define sipNameNr_bind 5397
#define sipName_bind &sipStrings_QtOpenGL[5397]
#define sipNameNr_Rgba 4948
#define sipName_Rgba &sipStrings_QtOpenGL[4948]
#define sipNameNr_find 5402
#define sipName_find &sipStrings_QtOpenGL[5402]
#define sipNameNr_rgba 5407
#define sipName_rgba &sipStrings_QtOpenGL[5407]
#define sipNameNr_font 5412
#define sipName_font &sipStrings_QtOpenGL[5412]
#define sipNameNr_mode 5417
#define sipName_mode &sipStrings_QtOpenGL[5417]
#define sipNameNr_name 5422
#define sipName_name &sipStrings_QtOpenGL[5422]
#define sipNameNr_Type 330
#define sipName_Type &sipStrings_QtOpenGL[330]
#define sipNameNr_base 5427
#define sipName_base &sipStrings_QtOpenGL[5427]
#define sipNameNr_fill 5432
#define sipName_fill &sipStrings_QtOpenGL[5432]
#define sipNameNr_from 5437
#define sipName_from &sipStrings_QtOpenGL[5437]
#define sipNameNr_sort 5442
#define sipName_sort &sipStrings_QtOpenGL[5442]
#define sipNameNr_read 5447
#define sipName_read &sipStrings_QtOpenGL[5447]
#define sipNameNr_type 5452
#define sipName_type &sipStrings_QtOpenGL[5452]
#define sipNameNr_link 5457
#define sipName_link &sipStrings_QtOpenGL[5457]
#define sipNameNr_size 5462
#define sipName_size &sipStrings_QtOpenGL[5462]
#define sipNameNr_log 5467
#define sipName_log &sipStrings_QtOpenGL[5467]
#define sipNameNr_QGL 5471
#define sipName_QGL &sipStrings_QtOpenGL[5471]
#define sipNameNr_pen 5475
#define sipName_pen &sipStrings_QtOpenGL[5475]
#define sipNameNr_end 5479
#define sipName_end &sipStrings_QtOpenGL[5479]
#define sipNameNr_map 2910
#define sipName_map &sipStrings_QtOpenGL[2910]
#define sipNameNr_pos 5483
#define sipName_pos &sipStrings_QtOpenGL[5483]
#define sipNameNr_sw 5487
#define sipName_sw &sipStrings_QtOpenGL[5487]
#define sipNameNr_sy 5490
#define sipName_sy &sipStrings_QtOpenGL[5490]
#define sipNameNr_sx 5493
#define sipName_sx &sipStrings_QtOpenGL[5493]
#define sipNameNr_sh 5334
#define sipName_sh &sipStrings_QtOpenGL[5334]
#define sipNameNr_cs 5388
#define sipName_cs &sipStrings_QtOpenGL[5388]

#define sipMalloc                   sipAPI_QtOpenGL->api_malloc
#define sipFree                     sipAPI_QtOpenGL->api_free
#define sipBuildResult              sipAPI_QtOpenGL->api_build_result
#define sipCallMethod               sipAPI_QtOpenGL->api_call_method
#define sipCallProcedureMethod      sipAPI_QtOpenGL->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_QtOpenGL->api_call_error_handler
#define sipParseResultEx            sipAPI_QtOpenGL->api_parse_result_ex
#define sipParseResult              sipAPI_QtOpenGL->api_parse_result
#define sipParseArgs                sipAPI_QtOpenGL->api_parse_args
#define sipParseKwdArgs             sipAPI_QtOpenGL->api_parse_kwd_args
#define sipParsePair                sipAPI_QtOpenGL->api_parse_pair
#define sipCommonDtor               sipAPI_QtOpenGL->api_common_dtor
#define sipConvertFromSequenceIndex sipAPI_QtOpenGL->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_QtOpenGL->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_QtOpenGL->api_convert_to_void_ptr
#define sipAddException             sipAPI_QtOpenGL->api_add_exception
#define sipNoFunction               sipAPI_QtOpenGL->api_no_function
#define sipNoMethod                 sipAPI_QtOpenGL->api_no_method
#define sipAbstractMethod           sipAPI_QtOpenGL->api_abstract_method
#define sipBadClass                 sipAPI_QtOpenGL->api_bad_class
#define sipBadCatcherResult         sipAPI_QtOpenGL->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_QtOpenGL->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_QtOpenGL->api_bad_operator_arg
#define sipTrace                    sipAPI_QtOpenGL->api_trace
#define sipTransferBack             sipAPI_QtOpenGL->api_transfer_back
#define sipTransferTo               sipAPI_QtOpenGL->api_transfer_to
#define sipTransferBreak            sipAPI_QtOpenGL->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_QtOpenGL->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_QtOpenGL->api_wrapper_type
#define sipWrapperType_Type         sipAPI_QtOpenGL->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_QtOpenGL->api_voidptr_type
#define sipGetPyObject              sipAPI_QtOpenGL->api_get_pyobject
#define sipGetAddress               sipAPI_QtOpenGL->api_get_address
#define sipGetMixinAddress          sipAPI_QtOpenGL->api_get_mixin_address
#define sipGetCppPtr                sipAPI_QtOpenGL->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_QtOpenGL->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_QtOpenGL->api_is_py_method
#define sipCallHook                 sipAPI_QtOpenGL->api_call_hook
#define sipEndThread                sipAPI_QtOpenGL->api_end_thread
#define sipConnectRx                sipAPI_QtOpenGL->api_connect_rx
#define sipDisconnectRx             sipAPI_QtOpenGL->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_QtOpenGL->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_QtOpenGL->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_QtOpenGL->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_QtOpenGL->api_add_type_instance
#define sipFreeSipslot              sipAPI_QtOpenGL->api_free_sipslot
#define sipSameSlot                 sipAPI_QtOpenGL->api_same_slot
#define sipPySlotExtend             sipAPI_QtOpenGL->api_pyslot_extend
#define sipConvertRx                sipAPI_QtOpenGL->api_convert_rx
#define sipAddDelayedDtor           sipAPI_QtOpenGL->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_QtOpenGL->api_can_convert_to_type
#define sipConvertToType            sipAPI_QtOpenGL->api_convert_to_type
#define sipForceConvertToType       sipAPI_QtOpenGL->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_QtOpenGL->api_can_convert_to_enum
#define sipReleaseType              sipAPI_QtOpenGL->api_release_type
#define sipConvertFromType          sipAPI_QtOpenGL->api_convert_from_type
#define sipConvertFromNewType       sipAPI_QtOpenGL->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_QtOpenGL->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_QtOpenGL->api_convert_from_enum
#define sipGetState                 sipAPI_QtOpenGL->api_get_state
#define sipLong_AsUnsignedLong      sipAPI_QtOpenGL->api_long_as_unsigned_long
#define sipExportSymbol             sipAPI_QtOpenGL->api_export_symbol
#define sipImportSymbol             sipAPI_QtOpenGL->api_import_symbol
#define sipFindType                 sipAPI_QtOpenGL->api_find_type
#define sipFindNamedEnum            sipAPI_QtOpenGL->api_find_named_enum
#define sipBytes_AsChar             sipAPI_QtOpenGL->api_bytes_as_char
#define sipBytes_AsString           sipAPI_QtOpenGL->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_QtOpenGL->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_QtOpenGL->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_QtOpenGL->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_QtOpenGL->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_QtOpenGL->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_QtOpenGL->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_QtOpenGL->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_QtOpenGL->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_QtOpenGL->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_QtOpenGL->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_QtOpenGL->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_QtOpenGL->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_QtOpenGL->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_QtOpenGL->api_save_slot
#define sipClearAnySlotReference    sipAPI_QtOpenGL->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_QtOpenGL->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_QtOpenGL->api_deprecated
#define sipGetReference             sipAPI_QtOpenGL->api_get_reference
#define sipKeepReference            sipAPI_QtOpenGL->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_QtOpenGL->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_QtOpenGL->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_QtOpenGL->api_type_from_py_type_object
#define sipTypeScope                sipAPI_QtOpenGL->api_type_scope
#define sipResolveTypedef           sipAPI_QtOpenGL->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_QtOpenGL->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_QtOpenGL->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_QtOpenGL->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_QtOpenGL->api_enable_autoconversion
#define sipInitMixin                sipAPI_QtOpenGL->api_init_mixin
#define sipExportModule             sipAPI_QtOpenGL->api_export_module
#define sipInitModule               sipAPI_QtOpenGL->api_init_module
#define sipGetInterpreter           sipAPI_QtOpenGL->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_QtOpenGL->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_QtOpenGL->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_QtOpenGL->api_get_type_user_data
#define sipPyTypeDict               sipAPI_QtOpenGL->api_py_type_dict
#define sipPyTypeName               sipAPI_QtOpenGL->api_py_type_name
#define sipGetCFunction             sipAPI_QtOpenGL->api_get_c_function
#define sipGetMethod                sipAPI_QtOpenGL->api_get_method
#define sipFromMethod               sipAPI_QtOpenGL->api_from_method
#define sipGetDate                  sipAPI_QtOpenGL->api_get_date
#define sipFromDate                 sipAPI_QtOpenGL->api_from_date
#define sipGetDateTime              sipAPI_QtOpenGL->api_get_datetime
#define sipFromDateTime             sipAPI_QtOpenGL->api_from_datetime
#define sipGetTime                  sipAPI_QtOpenGL->api_get_time
#define sipFromTime                 sipAPI_QtOpenGL->api_from_time
#define sipIsUserType               sipAPI_QtOpenGL->api_is_user_type
#define sipGetFrame                 sipAPI_QtOpenGL->api_get_frame
#define sipCheckPluginForType       sipAPI_QtOpenGL->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_QtOpenGL->api_unicode_new
#define sipUnicodeWrite             sipAPI_QtOpenGL->api_unicode_write
#define sipUnicodeData              sipAPI_QtOpenGL->api_unicode_data
#define sipGetBufferInfo            sipAPI_QtOpenGL->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_QtOpenGL->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_QtOpenGL->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_QtOpenGL->api_is_derived_class
#define sipGetUserObject            sipAPI_QtOpenGL->api_get_user_object
#define sipSetUserObject            sipAPI_QtOpenGL->api_set_user_object

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_QtOpenGL->api_map_string_to_class
#define sipMapIntToClass            sipAPI_QtOpenGL->api_map_int_to_class
#define sipFindClass                sipAPI_QtOpenGL->api_find_class
#define sipFindMappedType           sipAPI_QtOpenGL->api_find_mapped_type
#define sipConvertToArray           sipAPI_QtOpenGL->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_QtOpenGL->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_QtOpenGL->api_enable_gc
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_QtOpenGL->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_QtOpenGL[];

#define sipType_QGL sipExportedTypes_QtOpenGL[0]
#define sipClass_QGL sipExportedTypes_QtOpenGL[0]->u.td_wrapper_type

#define sipType_QGL_FormatOption sipExportedTypes_QtOpenGL[1]
#define sipEnum_QGL_FormatOption sipExportedTypes_QtOpenGL[1]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtOpenGL_QGL;

#define sipType_QGL_FormatOptions sipExportedTypes_QtOpenGL[2]
#define sipClass_QGL_FormatOptions sipExportedTypes_QtOpenGL[2]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtOpenGL_QGL_FormatOptions;

#define sipType_QGLFormat sipExportedTypes_QtOpenGL[11]
#define sipClass_QGLFormat sipExportedTypes_QtOpenGL[11]->u.td_wrapper_type

#define sipType_QGLFormat_OpenGLContextProfile sipExportedTypes_QtOpenGL[12]
#define sipEnum_QGLFormat_OpenGLContextProfile sipExportedTypes_QtOpenGL[12]->u.td_py_type

#define sipType_QGLFormat_OpenGLVersionFlag sipExportedTypes_QtOpenGL[13]
#define sipEnum_QGLFormat_OpenGLVersionFlag sipExportedTypes_QtOpenGL[13]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtOpenGL_QGLFormat;

#define sipType_QGLFormat_OpenGLVersionFlags sipExportedTypes_QtOpenGL[14]
#define sipClass_QGLFormat_OpenGLVersionFlags sipExportedTypes_QtOpenGL[14]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtOpenGL_QGLFormat_OpenGLVersionFlags;

#define sipType_QGLContext sipExportedTypes_QtOpenGL[8]
#define sipClass_QGLContext sipExportedTypes_QtOpenGL[8]->u.td_wrapper_type

#define sipType_QGLContext_BindOption sipExportedTypes_QtOpenGL[9]
#define sipEnum_QGLContext_BindOption sipExportedTypes_QtOpenGL[9]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtOpenGL_QGLContext;

#define sipType_QGLContext_BindOptions sipExportedTypes_QtOpenGL[10]
#define sipClass_QGLContext_BindOptions sipExportedTypes_QtOpenGL[10]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtOpenGL_QGLContext_BindOptions;

#define sipType_QGLWidget sipExportedTypes_QtOpenGL[23]
#define sipClass_QGLWidget sipExportedTypes_QtOpenGL[23]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtOpenGL_QGLWidget;

#define sipType_QGLBuffer sipExportedTypes_QtOpenGL[3]
#define sipClass_QGLBuffer sipExportedTypes_QtOpenGL[3]->u.td_wrapper_type

#define sipType_QGLBuffer_UsagePattern sipExportedTypes_QtOpenGL[6]
#define sipEnum_QGLBuffer_UsagePattern sipExportedTypes_QtOpenGL[6]->u.td_py_type

#define sipType_QGLBuffer_Type sipExportedTypes_QtOpenGL[5]
#define sipEnum_QGLBuffer_Type sipExportedTypes_QtOpenGL[5]->u.td_py_type

#define sipType_QGLBuffer_Access sipExportedTypes_QtOpenGL[4]
#define sipEnum_QGLBuffer_Access sipExportedTypes_QtOpenGL[4]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtOpenGL_QGLBuffer;

#define sipType_QGLColormap sipExportedTypes_QtOpenGL[7]
#define sipClass_QGLColormap sipExportedTypes_QtOpenGL[7]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtOpenGL_QGLColormap;

#define sipType_QGLFramebufferObject sipExportedTypes_QtOpenGL[15]
#define sipClass_QGLFramebufferObject sipExportedTypes_QtOpenGL[15]->u.td_wrapper_type

#define sipType_QGLFramebufferObject_Attachment sipExportedTypes_QtOpenGL[16]
#define sipEnum_QGLFramebufferObject_Attachment sipExportedTypes_QtOpenGL[16]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtOpenGL_QGLFramebufferObject;

#define sipType_QGLFramebufferObjectFormat sipExportedTypes_QtOpenGL[17]
#define sipClass_QGLFramebufferObjectFormat sipExportedTypes_QtOpenGL[17]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtOpenGL_QGLFramebufferObjectFormat;

#define sipType_QGLPixelBuffer sipExportedTypes_QtOpenGL[18]
#define sipClass_QGLPixelBuffer sipExportedTypes_QtOpenGL[18]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtOpenGL_QGLPixelBuffer;

#define sipType_QGLShader sipExportedTypes_QtOpenGL[19]
#define sipClass_QGLShader sipExportedTypes_QtOpenGL[19]->u.td_wrapper_type

#define sipType_QGLShader_ShaderTypeBit sipExportedTypes_QtOpenGL[21]
#define sipEnum_QGLShader_ShaderTypeBit sipExportedTypes_QtOpenGL[21]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtOpenGL_QGLShader;

#define sipType_QGLShader_ShaderType sipExportedTypes_QtOpenGL[20]
#define sipClass_QGLShader_ShaderType sipExportedTypes_QtOpenGL[20]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtOpenGL_QGLShader_ShaderType;

#define sipType_QGLShaderProgram sipExportedTypes_QtOpenGL[22]
#define sipClass_QGLShaderProgram sipExportedTypes_QtOpenGL[22]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtOpenGL_QGLShaderProgram;

#define sipType_QList_0101QGLShader sipExportedTypes_QtOpenGL[24]

extern sipMappedTypeDef sipTypeDef_QtOpenGL_QList_0101QGLShader;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_QtOpenGL;
extern sipExportedModuleDef sipModuleAPI_QtOpenGL;
extern sipTypeDef *sipExportedTypes_QtOpenGL[];

#define sipType_Qt_InputMethodQuery sipImportedTypes_QtOpenGL_QtCore[13].it_td
#define sipEnum_Qt_InputMethodQuery sipImportedTypes_QtOpenGL_QtCore[13].it_td->u.td_py_type

#define sipType_Qt_WindowFlags sipImportedTypes_QtOpenGL_QtCore[14].it_td
#define sipClass_Qt_WindowFlags sipImportedTypes_QtOpenGL_QtCore[14].it_td->u.td_wrapper_type

#define sipType_QObject sipImportedTypes_QtOpenGL_QtCore[3].it_td
#define sipClass_QObject sipImportedTypes_QtOpenGL_QtCore[3].it_td->u.td_wrapper_type

#define sipType_QByteArray sipImportedTypes_QtOpenGL_QtCore[0].it_td
#define sipClass_QByteArray sipImportedTypes_QtOpenGL_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_QtOpenGL_QtCore[2].it_td
#define sipClass_QEvent sipImportedTypes_QtOpenGL_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_QtOpenGL_QtCore[11].it_td
#define sipClass_QTimerEvent sipImportedTypes_QtOpenGL_QtCore[11].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_QtOpenGL_QtCore[1].it_td
#define sipClass_QChildEvent sipImportedTypes_QtOpenGL_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QPoint sipImportedTypes_QtOpenGL_QtCore[4].it_td
#define sipClass_QPoint sipImportedTypes_QtOpenGL_QtCore[4].it_td->u.td_wrapper_type

#define sipType_QPointF sipImportedTypes_QtOpenGL_QtCore[5].it_td
#define sipClass_QPointF sipImportedTypes_QtOpenGL_QtCore[5].it_td->u.td_wrapper_type

#define sipType_QRect sipImportedTypes_QtOpenGL_QtCore[6].it_td
#define sipClass_QRect sipImportedTypes_QtOpenGL_QtCore[6].it_td->u.td_wrapper_type

#define sipType_QRectF sipImportedTypes_QtOpenGL_QtCore[7].it_td
#define sipClass_QRectF sipImportedTypes_QtOpenGL_QtCore[7].it_td->u.td_wrapper_type

#define sipType_QSize sipImportedTypes_QtOpenGL_QtCore[8].it_td
#define sipClass_QSize sipImportedTypes_QtOpenGL_QtCore[8].it_td->u.td_wrapper_type

#define sipType_QSizeF sipImportedTypes_QtOpenGL_QtCore[9].it_td
#define sipClass_QSizeF sipImportedTypes_QtOpenGL_QtCore[9].it_td->u.td_wrapper_type

#define sipType_QVariant sipImportedTypes_QtOpenGL_QtCore[12].it_td
#define sipClass_QVariant sipImportedTypes_QtOpenGL_QtCore[12].it_td->u.td_wrapper_type

#define sipType_QString sipImportedTypes_QtOpenGL_QtCore[10].it_td
extern sipImportedTypeDef sipImportedTypes_QtOpenGL_QtCore[];

#define sipType_QPaintDevice sipImportedTypes_QtOpenGL_QtGui[25].it_td
#define sipClass_QPaintDevice sipImportedTypes_QtOpenGL_QtGui[25].it_td->u.td_wrapper_type

#define sipType_QPaintDevice_PaintDeviceMetric sipImportedTypes_QtOpenGL_QtGui[26].it_td
#define sipEnum_QPaintDevice_PaintDeviceMetric sipImportedTypes_QtOpenGL_QtGui[26].it_td->u.td_py_type

#define sipType_QWidget sipImportedTypes_QtOpenGL_QtGui[40].it_td
#define sipClass_QWidget sipImportedTypes_QtOpenGL_QtGui[40].it_td->u.td_wrapper_type

#define sipType_QPixmap sipImportedTypes_QtOpenGL_QtGui[31].it_td
#define sipClass_QPixmap sipImportedTypes_QtOpenGL_QtGui[31].it_td->u.td_wrapper_type

#define sipType_QColor sipImportedTypes_QtOpenGL_QtGui[2].it_td
#define sipClass_QColor sipImportedTypes_QtOpenGL_QtGui[2].it_td->u.td_wrapper_type

#define sipType_QMouseEvent sipImportedTypes_QtOpenGL_QtGui[23].it_td
#define sipClass_QMouseEvent sipImportedTypes_QtOpenGL_QtGui[23].it_td->u.td_wrapper_type

#define sipType_QWheelEvent sipImportedTypes_QtOpenGL_QtGui[39].it_td
#define sipClass_QWheelEvent sipImportedTypes_QtOpenGL_QtGui[39].it_td->u.td_wrapper_type

#define sipType_QTabletEvent sipImportedTypes_QtOpenGL_QtGui[34].it_td
#define sipClass_QTabletEvent sipImportedTypes_QtOpenGL_QtGui[34].it_td->u.td_wrapper_type

#define sipType_QKeyEvent sipImportedTypes_QtOpenGL_QtGui[13].it_td
#define sipClass_QKeyEvent sipImportedTypes_QtOpenGL_QtGui[13].it_td->u.td_wrapper_type

#define sipType_QFocusEvent sipImportedTypes_QtOpenGL_QtGui[8].it_td
#define sipClass_QFocusEvent sipImportedTypes_QtOpenGL_QtGui[8].it_td->u.td_wrapper_type

#define sipType_QPaintEvent sipImportedTypes_QtOpenGL_QtGui[29].it_td
#define sipClass_QPaintEvent sipImportedTypes_QtOpenGL_QtGui[29].it_td->u.td_wrapper_type

#define sipType_QMoveEvent sipImportedTypes_QtOpenGL_QtGui[24].it_td
#define sipClass_QMoveEvent sipImportedTypes_QtOpenGL_QtGui[24].it_td->u.td_wrapper_type

#define sipType_QResizeEvent sipImportedTypes_QtOpenGL_QtGui[32].it_td
#define sipClass_QResizeEvent sipImportedTypes_QtOpenGL_QtGui[32].it_td->u.td_wrapper_type

#define sipType_QCloseEvent sipImportedTypes_QtOpenGL_QtGui[1].it_td
#define sipClass_QCloseEvent sipImportedTypes_QtOpenGL_QtGui[1].it_td->u.td_wrapper_type

#define sipType_QShowEvent sipImportedTypes_QtOpenGL_QtGui[33].it_td
#define sipClass_QShowEvent sipImportedTypes_QtOpenGL_QtGui[33].it_td->u.td_wrapper_type

#define sipType_QHideEvent sipImportedTypes_QtOpenGL_QtGui[10].it_td
#define sipClass_QHideEvent sipImportedTypes_QtOpenGL_QtGui[10].it_td->u.td_wrapper_type

#define sipType_QContextMenuEvent sipImportedTypes_QtOpenGL_QtGui[3].it_td
#define sipClass_QContextMenuEvent sipImportedTypes_QtOpenGL_QtGui[3].it_td->u.td_wrapper_type

#define sipType_QInputMethodEvent sipImportedTypes_QtOpenGL_QtGui[12].it_td
#define sipClass_QInputMethodEvent sipImportedTypes_QtOpenGL_QtGui[12].it_td->u.td_wrapper_type

#define sipType_QDropEvent sipImportedTypes_QtOpenGL_QtGui[7].it_td
#define sipClass_QDropEvent sipImportedTypes_QtOpenGL_QtGui[7].it_td->u.td_wrapper_type

#define sipType_QDragMoveEvent sipImportedTypes_QtOpenGL_QtGui[6].it_td
#define sipClass_QDragMoveEvent sipImportedTypes_QtOpenGL_QtGui[6].it_td->u.td_wrapper_type

#define sipType_QDragEnterEvent sipImportedTypes_QtOpenGL_QtGui[4].it_td
#define sipClass_QDragEnterEvent sipImportedTypes_QtOpenGL_QtGui[4].it_td->u.td_wrapper_type

#define sipType_QDragLeaveEvent sipImportedTypes_QtOpenGL_QtGui[5].it_td
#define sipClass_QDragLeaveEvent sipImportedTypes_QtOpenGL_QtGui[5].it_td->u.td_wrapper_type

#define sipType_QActionEvent sipImportedTypes_QtOpenGL_QtGui[0].it_td
#define sipClass_QActionEvent sipImportedTypes_QtOpenGL_QtGui[0].it_td->u.td_wrapper_type

#define sipType_QFont sipImportedTypes_QtOpenGL_QtGui[9].it_td
#define sipClass_QFont sipImportedTypes_QtOpenGL_QtGui[9].it_td->u.td_wrapper_type

#define sipType_QMatrix4x3 sipImportedTypes_QtOpenGL_QtGui[21].it_td
#define sipClass_QMatrix4x3 sipImportedTypes_QtOpenGL_QtGui[21].it_td->u.td_wrapper_type

#define sipType_QMatrix4x2 sipImportedTypes_QtOpenGL_QtGui[20].it_td
#define sipClass_QMatrix4x2 sipImportedTypes_QtOpenGL_QtGui[20].it_td->u.td_wrapper_type

#define sipType_QMatrix3x4 sipImportedTypes_QtOpenGL_QtGui[19].it_td
#define sipClass_QMatrix3x4 sipImportedTypes_QtOpenGL_QtGui[19].it_td->u.td_wrapper_type

#define sipType_QMatrix3x3 sipImportedTypes_QtOpenGL_QtGui[18].it_td
#define sipClass_QMatrix3x3 sipImportedTypes_QtOpenGL_QtGui[18].it_td->u.td_wrapper_type

#define sipType_QMatrix3x2 sipImportedTypes_QtOpenGL_QtGui[17].it_td
#define sipClass_QMatrix3x2 sipImportedTypes_QtOpenGL_QtGui[17].it_td->u.td_wrapper_type

#define sipType_QMatrix2x4 sipImportedTypes_QtOpenGL_QtGui[16].it_td
#define sipClass_QMatrix2x4 sipImportedTypes_QtOpenGL_QtGui[16].it_td->u.td_wrapper_type

#define sipType_QMatrix2x3 sipImportedTypes_QtOpenGL_QtGui[15].it_td
#define sipClass_QMatrix2x3 sipImportedTypes_QtOpenGL_QtGui[15].it_td->u.td_wrapper_type

#define sipType_QMatrix2x2 sipImportedTypes_QtOpenGL_QtGui[14].it_td
#define sipClass_QMatrix2x2 sipImportedTypes_QtOpenGL_QtGui[14].it_td->u.td_wrapper_type

#define sipType_QImage sipImportedTypes_QtOpenGL_QtGui[11].it_td
#define sipClass_QImage sipImportedTypes_QtOpenGL_QtGui[11].it_td->u.td_wrapper_type

#define sipType_QMatrix4x4 sipImportedTypes_QtOpenGL_QtGui[22].it_td
#define sipClass_QMatrix4x4 sipImportedTypes_QtOpenGL_QtGui[22].it_td->u.td_wrapper_type

#define sipType_QPaintEngine sipImportedTypes_QtOpenGL_QtGui[27].it_td
#define sipClass_QPaintEngine sipImportedTypes_QtOpenGL_QtGui[27].it_td->u.td_wrapper_type

#define sipType_QPaintEngine_Type sipImportedTypes_QtOpenGL_QtGui[28].it_td
#define sipEnum_QPaintEngine_Type sipImportedTypes_QtOpenGL_QtGui[28].it_td->u.td_py_type

#define sipType_QPalette sipImportedTypes_QtOpenGL_QtGui[30].it_td
#define sipClass_QPalette sipImportedTypes_QtOpenGL_QtGui[30].it_td->u.td_wrapper_type

#define sipType_QTransform sipImportedTypes_QtOpenGL_QtGui[35].it_td
#define sipClass_QTransform sipImportedTypes_QtOpenGL_QtGui[35].it_td->u.td_wrapper_type

#define sipType_QVector2D sipImportedTypes_QtOpenGL_QtGui[36].it_td
#define sipClass_QVector2D sipImportedTypes_QtOpenGL_QtGui[36].it_td->u.td_wrapper_type

#define sipType_QVector3D sipImportedTypes_QtOpenGL_QtGui[37].it_td
#define sipClass_QVector3D sipImportedTypes_QtOpenGL_QtGui[37].it_td->u.td_wrapper_type

#define sipType_QVector4D sipImportedTypes_QtOpenGL_QtGui[38].it_td
#define sipClass_QVector4D sipImportedTypes_QtOpenGL_QtGui[38].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_QtOpenGL_QtGui[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_QtOpenGL_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_QtOpenGL_qt_metacall;

typedef int (*sip_qt_metacast_func)(sipSimpleWrapper *, sipTypeDef *, const char *);
extern sip_qt_metacast_func sip_QtOpenGL_qt_metacast;
#line 480 "/home/thais/Faculdade/TCC/NEW/PyQt4_gpl_x11-4.12/sip/QtOpenGL/qgl.sip"
#include <qpyopengl_api.h>
#line 1398 "/home/thais/Faculdade/TCC/NEW/PyQt4_gpl_x11-4.12/QtOpenGL/sipAPIQtOpenGL.h"

#endif
