/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.2
 *
 * Copyright (c) 2016 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt4.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef _QtDBusAPI_H
#define _QtDBusAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Deprecated_5_0
#define SIP_FEATURE_PyQt_NoOpenGLES
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_SystemTrayIcon
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SizeGrip
#define SIP_FEATURE_PyQt_OpenSSL
#define SIP_FEATURE_Py_DateTime
#define SIP_FEATURE_PyQt_NoQtPrintRangeBug
#define SIP_FEATURE_PyQt_WhatsThis
#define SIP_FEATURE_PyQt_ToolTip
#define SIP_FEATURE_PyQt_StatusTip
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11
#define SIP_TIMELINE_Qt_4_8_7


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_0 0
#define sipName_0 &sipStrings_QtDBus[0]
#define sipNameNr_QDBusConnectionInterface__ServiceReplacementOptions 59
#define sipName_QDBusConnectionInterface__ServiceReplacementOptions &sipStrings_QtDBus[59]
#define sipNameNr_QDBusConnectionInterface__RegisterServiceReply 111
#define sipName_QDBusConnectionInterface__RegisterServiceReply &sipStrings_QtDBus[111]
#define sipNameNr_QDBusConnectionInterface__ServiceQueueOptions 158
#define sipName_QDBusConnectionInterface__ServiceQueueOptions &sipStrings_QtDBus[158]
#define sipNameNr_QDBusConnection__ConnectionCapabilities 204
#define sipName_QDBusConnection__ConnectionCapabilities &sipStrings_QtDBus[204]
#define sipNameNr_QDBusConnection__ConnectionCapability 244
#define sipName_QDBusConnection__ConnectionCapability &sipStrings_QtDBus[244]
#define sipNameNr_QDBusServiceWatcher__WatchModeFlag 282
#define sipName_QDBusServiceWatcher__WatchModeFlag &sipStrings_QtDBus[282]
#define sipNameNr_QDBusConnection__RegisterOptions 317
#define sipName_QDBusConnection__RegisterOptions &sipStrings_QtDBus[317]
#define sipNameNr_QDBusConnection__UnregisterMode 350
#define sipName_QDBusConnection__UnregisterMode &sipStrings_QtDBus[350]
#define sipNameNr_QDBusConnection__RegisterOption 382
#define sipName_QDBusConnection__RegisterOption &sipStrings_QtDBus[382]
#define sipNameNr_QDBusServiceWatcher__WatchMode 414
#define sipName_QDBusServiceWatcher__WatchMode &sipStrings_QtDBus[414]
#define sipNameNr_ExportNonScriptableInvokables 445
#define sipName_ExportNonScriptableInvokables &sipStrings_QtDBus[445]
#define sipNameNr_ExportNonScriptableProperties 475
#define sipName_ExportNonScriptableProperties &sipStrings_QtDBus[475]
#define sipNameNr_PyQt4_QtCore_pyqtWrapperType 505
#define sipName_PyQt4_QtCore_pyqtWrapperType &sipStrings_QtDBus[505]
#define sipNameNr_ExportNonScriptableContents 534
#define sipName_ExportNonScriptableContents &sipStrings_QtDBus[534]
#define sipNameNr_ExportNonScriptableSignals 562
#define sipName_ExportNonScriptableSignals &sipStrings_QtDBus[562]
#define sipNameNr_ExportScriptableInvokables 589
#define sipName_ExportScriptableInvokables &sipStrings_QtDBus[589]
#define sipNameNr_ExportScriptableProperties 616
#define sipName_ExportScriptableProperties &sipStrings_QtDBus[616]
#define sipNameNr_QDBusMessage__MessageType 643
#define sipName_QDBusMessage__MessageType &sipStrings_QtDBus[643]
#define sipNameNr_ServiceReplacementOptions 85
#define sipName_ServiceReplacementOptions &sipStrings_QtDBus[85]
#define sipNameNr_UnixFileDescriptorPassing 669
#define sipName_UnixFileDescriptorPassing &sipStrings_QtDBus[669]
#define sipNameNr_asyncCallWithArgumentList 695
#define sipName_asyncCallWithArgumentList &sipStrings_QtDBus[695]
#define sipNameNr_QDBusConnectionInterface 721
#define sipName_QDBusConnectionInterface &sipStrings_QtDBus[721]
#define sipNameNr_ExportNonScriptableSlots 746
#define sipName_ExportNonScriptableSlots &sipStrings_QtDBus[746]
#define sipNameNr_ExportScriptableContents 771
#define sipName_ExportScriptableContents &sipStrings_QtDBus[771]
#define sipNameNr_QDBusConnection__BusType 796
#define sipName_QDBusConnection__BusType &sipStrings_QtDBus[796]
#define sipNameNr_821 821
#define sipName_821 &sipStrings_QtDBus[821]
#define sipNameNr_QDBusUnixFileDescriptor 845
#define sipName_QDBusUnixFileDescriptor &sipStrings_QtDBus[845]
#define sipNameNr_QDBusPendingCallWatcher 869
#define sipName_QDBusPendingCallWatcher &sipStrings_QtDBus[869]
#define sipNameNr_ExportScriptableSignals 893
#define sipName_ExportScriptableSignals &sipStrings_QtDBus[893]
#define sipNameNr_WatchForUnregistration 917
#define sipName_WatchForUnregistration &sipStrings_QtDBus[917]
#define sipNameNr_callWithCallbackFailed 940
#define sipName_callWithCallbackFailed &sipStrings_QtDBus[940]
#define sipNameNr_registeredServiceNames 963
#define sipName_registeredServiceNames &sipStrings_QtDBus[963]
#define sipNameNr_ReplaceExistingService 986
#define sipName_ReplaceExistingService &sipStrings_QtDBus[986]
#define sipNameNr_connectionCapabilities 1009
#define sipName_connectionCapabilities &sipStrings_QtDBus[1009]
#define sipNameNr_ConnectionCapabilities 221
#define sipName_ConnectionCapabilities &sipStrings_QtDBus[221]
#define sipNameNr_QDBusAbstractInterface 1032
#define sipName_QDBusAbstractInterface &sipStrings_QtDBus[1032]
#define sipNameNr_QDBusError__ErrorType 1055
#define sipName_QDBusError__ErrorType &sipStrings_QtDBus[1055]
#define sipNameNr_ExportScriptableSlots 1077
#define sipName_ExportScriptableSlots &sipStrings_QtDBus[1077]
#define sipNameNr_removeWatchedService 1099
#define sipName_removeWatchedService &sipStrings_QtDBus[1099]
#define sipNameNr_WatchForRegistration 1120
#define sipName_WatchForRegistration &sipStrings_QtDBus[1120]
#define sipNameNr_ServiceNotRegistered 1141
#define sipName_ServiceNotRegistered &sipStrings_QtDBus[1141]
#define sipNameNr_RegisterServiceReply 137
#define sipName_RegisterServiceReply &sipStrings_QtDBus[137]
#define sipNameNr_DontAllowReplacement 1162
#define sipName_DontAllowReplacement &sipStrings_QtDBus[1162]
#define sipNameNr_ConnectionCapability 261
#define sipName_ConnectionCapability &sipStrings_QtDBus[261]
#define sipNameNr_callWithArgumentList 1183
#define sipName_callWithArgumentList &sipStrings_QtDBus[1183]
#define sipNameNr_QDBusAbstractAdaptor 1204
#define sipName_QDBusAbstractAdaptor &sipStrings_QtDBus[1204]
#define sipNameNr_1225 1225
#define sipName_1225 &sipStrings_QtDBus[1225]
#define sipNameNr_QPyDBusPendingReply 1245
#define sipName_QPyDBusPendingReply &sipStrings_QtDBus[1245]
#define sipNameNr_WatchForOwnerChange 1265
#define sipName_WatchForOwnerChange &sipStrings_QtDBus[1265]
#define sipNameNr_QDBusServiceWatcher 1285
#define sipName_QDBusServiceWatcher &sipStrings_QtDBus[1285]
#define sipNameNr_setAutoStartService 1305
#define sipName_setAutoStartService &sipStrings_QtDBus[1305]
#define sipNameNr_serviceOwnerChanged 1325
#define sipName_serviceOwnerChanged &sipStrings_QtDBus[1325]
#define sipNameNr_serviceUnregistered 1345
#define sipName_serviceUnregistered &sipStrings_QtDBus[1345]
#define sipNameNr_isServiceRegistered 1365
#define sipName_isServiceRegistered &sipStrings_QtDBus[1365]
#define sipNameNr_ServiceQueueOptions 184
#define sipName_ServiceQueueOptions &sipStrings_QtDBus[184]
#define sipNameNr_ExportAllInvokables 1385
#define sipName_ExportAllInvokables &sipStrings_QtDBus[1385]
#define sipNameNr_ExportAllProperties 1405
#define sipName_ExportAllProperties &sipStrings_QtDBus[1405]
#define sipNameNr_setAutoRelaySignals 1425
#define sipName_setAutoRelaySignals &sipStrings_QtDBus[1425]
#define sipNameNr_setWatchedServices 1445
#define sipName_setWatchedServices &sipStrings_QtDBus[1445]
#define sipNameNr_disconnectFromPeer 1464
#define sipName_disconnectFromPeer &sipStrings_QtDBus[1464]
#define sipNameNr_objectRegisteredAt 1483
#define sipName_objectRegisteredAt &sipStrings_QtDBus[1483]
#define sipNameNr_ExportChildObjects 1502
#define sipName_ExportChildObjects &sipStrings_QtDBus[1502]
#define sipNameNr_QDBusPendingReply 1521
#define sipName_QDBusPendingReply &sipStrings_QtDBus[1521]
#define sipNameNr_setFileDescriptor 1539
#define sipName_setFileDescriptor &sipStrings_QtDBus[1539]
#define sipNameNr_addWatchedService 1557
#define sipName_addWatchedService &sipStrings_QtDBus[1557]
#define sipNameNr_fromCompletedCall 1575
#define sipName_fromCompletedCall &sipStrings_QtDBus[1575]
#define sipNameNr_MethodCallMessage 1593
#define sipName_MethodCallMessage &sipStrings_QtDBus[1593]
#define sipNameNr_InvalidObjectPath 1611
#define sipName_InvalidObjectPath &sipStrings_QtDBus[1611]
#define sipNameNr_serviceRegistered 1629
#define sipName_serviceRegistered &sipStrings_QtDBus[1629]
#define sipNameNr_ServiceRegistered 1367
#define sipName_ServiceRegistered &sipStrings_QtDBus[1367]
#define sipNameNr_disconnectFromBus 1647
#define sipName_disconnectFromBus &sipStrings_QtDBus[1647]
#define sipNameNr_unregisterService 1665
#define sipName_unregisterService &sipStrings_QtDBus[1665]
#define sipNameNr_ExportAllContents 1683
#define sipName_ExportAllContents &sipStrings_QtDBus[1683]
#define sipNameNr_sip_simplewrapper 1701
#define sipName_sip_simplewrapper &sipStrings_QtDBus[1701]
#define sipNameNr_1719 1719
#define sipName_1719 &sipStrings_QtDBus[1719]
#define sipNameNr_1736 1736
#define sipName_1736 &sipStrings_QtDBus[1736]
#define sipNameNr_1753 1753
#define sipName_1753 &sipStrings_QtDBus[1753]
#define sipNameNr_QDBusPendingCall 1770
#define sipName_QDBusPendingCall &sipStrings_QtDBus[1770]
#define sipNameNr_autoStartService 1787
#define sipName_autoStartService &sipStrings_QtDBus[1787]
#define sipNameNr_createErrorReply 1804
#define sipName_createErrorReply &sipStrings_QtDBus[1804]
#define sipNameNr_createMethodCall 1821
#define sipName_createMethodCall &sipStrings_QtDBus[1821]
#define sipNameNr_InvalidInterface 1838
#define sipName_InvalidInterface &sipStrings_QtDBus[1838]
#define sipNameNr_UnknownInterface 1855
#define sipName_UnknownInterface &sipStrings_QtDBus[1855]
#define sipNameNr_InvalidSignature 1872
#define sipName_InvalidSignature &sipStrings_QtDBus[1872]
#define sipNameNr_AllowReplacement 1166
#define sipName_AllowReplacement &sipStrings_QtDBus[1166]
#define sipNameNr_DontQueueService 1889
#define sipName_DontQueueService &sipStrings_QtDBus[1889]
#define sipNameNr_unregisterObject 1906
#define sipName_unregisterObject &sipStrings_QtDBus[1906]
#define sipNameNr_ExportAllSignals 1923
#define sipName_ExportAllSignals &sipStrings_QtDBus[1923]
#define sipNameNr_callWithCallback 1940
#define sipName_callWithCallback &sipStrings_QtDBus[1940]
#define sipNameNr_autoRelaySignals 1957
#define sipName_autoRelaySignals &sipStrings_QtDBus[1957]
#define sipNameNr_disconnectNotify 1974
#define sipName_disconnectNotify &sipStrings_QtDBus[1974]
#define sipNameNr_watchedServices 1991
#define sipName_watchedServices &sipStrings_QtDBus[1991]
#define sipNameNr_setDelayedReply 2007
#define sipName_setDelayedReply &sipStrings_QtDBus[2007]
#define sipNameNr_isReplyRequired 2023
#define sipName_isReplyRequired &sipStrings_QtDBus[2023]
#define sipNameNr_QDBusObjectPath 2039
#define sipName_QDBusObjectPath &sipStrings_QtDBus[2039]
#define sipNameNr_registerService 1667
#define sipName_registerService &sipStrings_QtDBus[1667]
#define sipNameNr_RegisterOptions 334
#define sipName_RegisterOptions &sipStrings_QtDBus[334]
#define sipNameNr_ExportAllSignal 2055
#define sipName_ExportAllSignal &sipStrings_QtDBus[2055]
#define sipNameNr_QDBusConnection 2071
#define sipName_QDBusConnection &sipStrings_QtDBus[2071]
#define sipNameNr_QDBus__CallMode 2087
#define sipName_QDBus__CallMode &sipStrings_QtDBus[2087]
#define sipNameNr_waitForFinished 2103
#define sipName_waitForFinished &sipStrings_QtDBus[2103]
#define sipNameNr_fileDescriptor 2119
#define sipName_fileDescriptor &sipStrings_QtDBus[2119]
#define sipNameNr_isDelayedReply 2134
#define sipName_isDelayedReply &sipStrings_QtDBus[2134]
#define sipNameNr_InvalidMessage 2149
#define sipName_InvalidMessage &sipStrings_QtDBus[2149]
#define sipNameNr_QDBusInterface 2164
#define sipName_QDBusInterface &sipStrings_QtDBus[2164]
#define sipNameNr_QDBusSignature 2179
#define sipName_QDBusSignature &sipStrings_QtDBus[2179]
#define sipNameNr_InvalidService 2194
#define sipName_InvalidService &sipStrings_QtDBus[2194]
#define sipNameNr_LimitsExceeded 2209
#define sipName_LimitsExceeded &sipStrings_QtDBus[2209]
#define sipNameNr_ServiceUnknown 2224
#define sipName_ServiceUnknown &sipStrings_QtDBus[2224]
#define sipNameNr_localMachineId 2239
#define sipName_localMachineId &sipStrings_QtDBus[2239]
#define sipNameNr_registerObject 1908
#define sipName_registerObject &sipStrings_QtDBus[1908]
#define sipNameNr_UnregisterTree 2254
#define sipName_UnregisterTree &sipStrings_QtDBus[2254]
#define sipNameNr_UnregisterNode 2269
#define sipName_UnregisterNode &sipStrings_QtDBus[2269]
#define sipNameNr_UnregisterMode 367
#define sipName_UnregisterMode &sipStrings_QtDBus[367]
#define sipNameNr_ExportAllSlots 2284
#define sipName_ExportAllSlots &sipStrings_QtDBus[2284]
#define sipNameNr_ExportAdaptors 2299
#define sipName_ExportAdaptors &sipStrings_QtDBus[2299]
#define sipNameNr_RegisterOption 399
#define sipName_RegisterOption &sipStrings_QtDBus[399]
#define sipNameNr_beginStructure 2314
#define sipName_beginStructure &sipStrings_QtDBus[2314]
#define sipNameNr_setConnection 2329
#define sipName_setConnection &sipStrings_QtDBus[2329]
#define sipNameNr_WatchModeFlag 303
#define sipName_WatchModeFlag &sipStrings_QtDBus[303]
#define sipNameNr_SignalMessage 2343
#define sipName_SignalMessage &sipStrings_QtDBus[2343]
#define sipNameNr_InvalidMember 2357
#define sipName_InvalidMember &sipStrings_QtDBus[2357]
#define sipNameNr_UnknownObject 2371
#define sipName_UnknownObject &sipStrings_QtDBus[2371]
#define sipNameNr_InternalError 2385
#define sipName_InternalError &sipStrings_QtDBus[2385]
#define sipNameNr_UnknownMethod 2399
#define sipName_UnknownMethod &sipStrings_QtDBus[2399]
#define sipNameNr_ServiceQueued 2413
#define sipName_ServiceQueued &sipStrings_QtDBus[2413]
#define sipNameNr_connectToPeer 2427
#define sipName_connectToPeer &sipStrings_QtDBus[2427]
#define sipNameNr_ActivationBus 2441
#define sipName_ActivationBus &sipStrings_QtDBus[2441]
#define sipNameNr_beginMapEntry 2455
#define sipName_beginMapEntry &sipStrings_QtDBus[2455]
#define sipNameNr_QDBusArgument 2469
#define sipName_QDBusArgument &sipStrings_QtDBus[2469]
#define sipNameNr_connectNotify 1977
#define sipName_connectNotify &sipStrings_QtDBus[1977]
#define sipNameNr_QPyDBusReply 2483
#define sipName_QPyDBusReply &sipStrings_QtDBus[2483]
#define sipNameNr_setWatchMode 2496
#define sipName_setWatchMode &sipStrings_QtDBus[2496]
#define sipNameNr_setArguments 2509
#define sipName_setArguments &sipStrings_QtDBus[2509]
#define sipNameNr_errorMessage 2522
#define sipName_errorMessage &sipStrings_QtDBus[2522]
#define sipNameNr_createSignal 2535
#define sipName_createSignal &sipStrings_QtDBus[2535]
#define sipNameNr_ErrorMessage 2548
#define sipName_ErrorMessage &sipStrings_QtDBus[2548]
#define sipNameNr_ReplyMessage 2561
#define sipName_ReplyMessage &sipStrings_QtDBus[2561]
#define sipNameNr_QDBusMessage 2574
#define sipName_QDBusMessage &sipStrings_QtDBus[2574]
#define sipNameNr_QDBusVariant 2587
#define sipName_QDBusVariant &sipStrings_QtDBus[2587]
#define sipNameNr_setSignature 2600
#define sipName_setSignature &sipStrings_QtDBus[2600]
#define sipNameNr_Disconnected 2613
#define sipName_Disconnected &sipStrings_QtDBus[2613]
#define sipNameNr_AddressInUse 2626
#define sipName_AddressInUse &sipStrings_QtDBus[2626]
#define sipNameNr_AccessDenied 2639
#define sipName_AccessDenied &sipStrings_QtDBus[2639]
#define sipNameNr_NotSupported 2652
#define sipName_NotSupported &sipStrings_QtDBus[2652]
#define sipNameNr_startService 2665
#define sipName_startService &sipStrings_QtDBus[2665]
#define sipNameNr_serviceOwner 2678
#define sipName_serviceOwner &sipStrings_QtDBus[2678]
#define sipNameNr_QueueService 1893
#define sipName_QueueService &sipStrings_QtDBus[1893]
#define sipNameNr_connectToBus 2691
#define sipName_connectToBus &sipStrings_QtDBus[2691]
#define sipNameNr_BlockWithGui 2704
#define sipName_BlockWithGui &sipStrings_QtDBus[2704]
#define sipNameNr_endStructure 2717
#define sipName_endStructure &sipStrings_QtDBus[2717]
#define sipNameNr_PyQt4_QtDBus 2730
#define sipName_PyQt4_QtDBus &sipStrings_QtDBus[2730]
#define sipNameNr_isSupported 2743
#define sipName_isSupported &sipStrings_QtDBus[2743]
#define sipNameNr_createReply 2755
#define sipName_createReply &sipStrings_QtDBus[2755]
#define sipNameNr_createError 2767
#define sipName_createError &sipStrings_QtDBus[2767]
#define sipNameNr_MessageType 657
#define sipName_MessageType &sipStrings_QtDBus[657]
#define sipNameNr_InvalidArgs 2779
#define sipName_InvalidArgs &sipStrings_QtDBus[2779]
#define sipNameNr_baseService 2791
#define sipName_baseService &sipStrings_QtDBus[2791]
#define sipNameNr_isConnected 2803
#define sipName_isConnected &sipStrings_QtDBus[2803]
#define sipNameNr_endMapEntry 2815
#define sipName_endMapEntry &sipStrings_QtDBus[2815]
#define sipNameNr_customEvent 2827
#define sipName_customEvent &sipStrings_QtDBus[2827]
#define sipNameNr_eventFilter 2839
#define sipName_eventFilter &sipStrings_QtDBus[2839]
#define sipNameNr_errorString 2851
#define sipName_errorString &sipStrings_QtDBus[2851]
#define sipNameNr_QDBusReply 2863
#define sipName_QDBusReply &sipStrings_QtDBus[2863]
#define sipNameNr_argumentAt 2874
#define sipName_argumentAt &sipStrings_QtDBus[2874]
#define sipNameNr_setVariant 2885
#define sipName_setVariant &sipStrings_QtDBus[2885]
#define sipNameNr_BadAddress 2896
#define sipName_BadAddress &sipStrings_QtDBus[2896]
#define sipNameNr_QDBusError 2907
#define sipName_QDBusError &sipStrings_QtDBus[2907]
#define sipNameNr_serviceUid 2918
#define sipName_serviceUid &sipStrings_QtDBus[2918]
#define sipNameNr_servicePid 2929
#define sipName_servicePid &sipStrings_QtDBus[2929]
#define sipNameNr_sessionBus 2940
#define sipName_sessionBus &sipStrings_QtDBus[2940]
#define sipNameNr_SessionBus 2951
#define sipName_SessionBus &sipStrings_QtDBus[2951]
#define sipNameNr_AutoDetect 2962
#define sipName_AutoDetect &sipStrings_QtDBus[2962]
#define sipNameNr_beginArray 2973
#define sipName_beginArray &sipStrings_QtDBus[2973]
#define sipNameNr_setTimeout 2984
#define sipName_setTimeout &sipStrings_QtDBus[2984]
#define sipNameNr_connection 2995
#define sipName_connection &sipStrings_QtDBus[2995]
#define sipNameNr_isFinished 3006
#define sipName_isFinished &sipStrings_QtDBus[3006]
#define sipNameNr_fieldWidth 3017
#define sipName_fieldWidth &sipStrings_QtDBus[3017]
#define sipNameNr_childEvent 3028
#define sipName_childEvent &sipStrings_QtDBus[3028]
#define sipNameNr_timerEvent 3039
#define sipName_timerEvent &sipStrings_QtDBus[3039]
#define sipNameNr_disconnect 3050
#define sipName_disconnect &sipStrings_QtDBus[3050]
#define sipNameNr___lshift__ 3061
#define sipName___lshift__ &sipStrings_QtDBus[3061]
#define sipNameNr___invert__ 3072
#define sipName___invert__ &sipStrings_QtDBus[3072]
#define sipNameNr_watchMode 3083
#define sipName_watchMode &sipStrings_QtDBus[3083]
#define sipNameNr_WatchMode 435
#define sipName_WatchMode &sipStrings_QtDBus[435]
#define sipNameNr_fromError 3093
#define sipName_fromError &sipStrings_QtDBus[3093]
#define sipNameNr_errorName 3103
#define sipName_errorName &sipStrings_QtDBus[3103]
#define sipNameNr_NoNetwork 3113
#define sipName_NoNetwork &sipStrings_QtDBus[3113]
#define sipNameNr_ErrorType 1067
#define sipName_ErrorType &sipStrings_QtDBus[1067]
#define sipNameNr_systemBus 3123
#define sipName_systemBus &sipStrings_QtDBus[3123]
#define sipNameNr_SystemBus 3133
#define sipName_SystemBus &sipStrings_QtDBus[3133]
#define sipNameNr_asyncCall 3143
#define sipName_asyncCall &sipStrings_QtDBus[3143]
#define sipNameNr_lastError 3153
#define sipName_lastError &sipStrings_QtDBus[3153]
#define sipNameNr_interface 3163
#define sipName_interface &sipStrings_QtDBus[3163]
#define sipNameNr_directory 3173
#define sipName_directory &sipStrings_QtDBus[3173]
#define sipNameNr_signature 3183
#define sipName_signature &sipStrings_QtDBus[3183]
#define sipNameNr_arguments 3193
#define sipName_arguments &sipStrings_QtDBus[3193]
#define sipNameNr_precision 3203
#define sipName_precision &sipStrings_QtDBus[3203]
#define sipNameNr_TimedOut 3213
#define sipName_TimedOut &sipStrings_QtDBus[3213]
#define sipNameNr_NoServer 3222
#define sipName_NoServer &sipStrings_QtDBus[3222]
#define sipNameNr_NoMemory 3231
#define sipName_NoMemory &sipStrings_QtDBus[3231]
#define sipNameNr_CallMode 2094
#define sipName_CallMode &sipStrings_QtDBus[2094]
#define sipNameNr_beginMap 3240
#define sipName_beginMap &sipStrings_QtDBus[3240]
#define sipNameNr_behavior 3249
#define sipName_behavior &sipStrings_QtDBus[3249]
#define sipNameNr_fillChar 3258
#define sipName_fillChar &sipStrings_QtDBus[3258]
#define sipNameNr_endArray 3267
#define sipName_endArray &sipStrings_QtDBus[3267]
#define sipNameNr___hash__ 3276
#define sipName___hash__ &sipStrings_QtDBus[3276]
#define sipNameNr_finished 3285
#define sipName_finished &sipStrings_QtDBus[3285]
#define sipNameNr___bool__ 3294
#define sipName___bool__ &sipStrings_QtDBus[3294]
#define sipNameNr___ixor__ 3303
#define sipName___ixor__ &sipStrings_QtDBus[3303]
#define sipNameNr___iand__ 3312
#define sipName___iand__ &sipStrings_QtDBus[3312]
#define sipNameNr_isError 3321
#define sipName_isError &sipStrings_QtDBus[3321]
#define sipNameNr_Timeout 2987
#define sipName_Timeout &sipStrings_QtDBus[2987]
#define sipNameNr_NoReply 3329
#define sipName_NoReply &sipStrings_QtDBus[3329]
#define sipNameNr_roption 3337
#define sipName_roption &sipStrings_QtDBus[3337]
#define sipNameNr_qoption 3345
#define sipName_qoption &sipStrings_QtDBus[3345]
#define sipNameNr_BusType 813
#define sipName_BusType &sipStrings_QtDBus[813]
#define sipNameNr_NoBlock 3353
#define sipName_NoBlock &sipStrings_QtDBus[3353]
#define sipNameNr_service 3361
#define sipName_service &sipStrings_QtDBus[3361]
#define sipNameNr_variant 3369
#define sipName_variant &sipStrings_QtDBus[3369]
#define sipNameNr_connect 3053
#define sipName_connect &sipStrings_QtDBus[3053]
#define sipNameNr_options 3377
#define sipName_options &sipStrings_QtDBus[3377]
#define sipNameNr_NoError 3385
#define sipName_NoError &sipStrings_QtDBus[3385]
#define sipNameNr_timeout 3393
#define sipName_timeout &sipStrings_QtDBus[3393]
#define sipNameNr_setPath 3401
#define sipName_setPath &sipStrings_QtDBus[3401]
#define sipNameNr_isValid 3409
#define sipName_isValid &sipStrings_QtDBus[3409]
#define sipNameNr_filters 3417
#define sipName_filters &sipStrings_QtDBus[3417]
#define sipNameNr_message 3425
#define sipName_message &sipStrings_QtDBus[3425]
#define sipNameNr___xor__ 3433
#define sipName___xor__ &sipStrings_QtDBus[3433]
#define sipNameNr___ior__ 3441
#define sipName___ior__ &sipStrings_QtDBus[3441]
#define sipNameNr___and__ 3449
#define sipName___and__ &sipStrings_QtDBus[3449]
#define sipNameNr___int__ 3457
#define sipName___int__ &sipStrings_QtDBus[3457]
#define sipNameNr_Failed 956
#define sipName_Failed &sipStrings_QtDBus[956]
#define sipNameNr_endMap 3465
#define sipName_endMap &sipStrings_QtDBus[3465]
#define sipNameNr_proper 3472
#define sipName_proper &sipStrings_QtDBus[3472]
#define sipNameNr_member 3479
#define sipName_member &sipStrings_QtDBus[3479]
#define sipNameNr_sender 3486
#define sipName_sender &sipStrings_QtDBus[3486]
#define sipNameNr_value9 3493
#define sipName_value9 &sipStrings_QtDBus[3493]
#define sipNameNr_value8 3500
#define sipName_value8 &sipStrings_QtDBus[3500]
#define sipNameNr_value7 3507
#define sipName_value7 &sipStrings_QtDBus[3507]
#define sipNameNr_value6 3514
#define sipName_value6 &sipStrings_QtDBus[3514]
#define sipNameNr_value5 3521
#define sipName_value5 &sipStrings_QtDBus[3521]
#define sipNameNr_value4 3528
#define sipName_value4 &sipStrings_QtDBus[3528]
#define sipNameNr_value3 3535
#define sipName_value3 &sipStrings_QtDBus[3535]
#define sipNameNr_value2 3542
#define sipName_value2 &sipStrings_QtDBus[3542]
#define sipNameNr_value1 3549
#define sipName_value1 &sipStrings_QtDBus[3549]
#define sipNameNr_value0 3556
#define sipName_value0 &sipStrings_QtDBus[3556]
#define sipNameNr_symbol 3563
#define sipName_symbol &sipStrings_QtDBus[3563]
#define sipNameNr_suffix 3570
#define sipName_suffix &sipStrings_QtDBus[3570]
#define sipNameNr_prefix 3577
#define sipName_prefix &sipStrings_QtDBus[3577]
#define sipNameNr_format 3584
#define sipName_format &sipStrings_QtDBus[3584]
#define sipNameNr___ge__ 3591
#define sipName___ge__ &sipStrings_QtDBus[3591]
#define sipNameNr___lt__ 3598
#define sipName___lt__ &sipStrings_QtDBus[3598]
#define sipNameNr_parent 3605
#define sipName_parent &sipStrings_QtDBus[3605]
#define sipNameNr___ne__ 3612
#define sipName___ne__ &sipStrings_QtDBus[3612]
#define sipNameNr___eq__ 3619
#define sipName___eq__ &sipStrings_QtDBus[3619]
#define sipNameNr___or__ 3626
#define sipName___or__ &sipStrings_QtDBus[3626]
#define sipNameNr_reply 3633
#define sipName_reply &sipStrings_QtDBus[3633]
#define sipNameNr_Other 3639
#define sipName_Other &sipStrings_QtDBus[3639]
#define sipNameNr_Block 3355
#define sipName_Block &sipStrings_QtDBus[3355]
#define sipNameNr_QDBus 3645
#define sipName_QDBus &sipStrings_QtDBus[3645]
#define sipNameNr_value 3651
#define sipName_value &sipStrings_QtDBus[3651]
#define sipNameNr_error 3657
#define sipName_error &sipStrings_QtDBus[3657]
#define sipNameNr_flags 3663
#define sipName_flags &sipStrings_QtDBus[3663]
#define sipNameNr_event 3669
#define sipName_event &sipStrings_QtDBus[3669]
#define sipNameNr_msecs 3675
#define sipName_msecs &sipStrings_QtDBus[3675]
#define sipNameNr_send 3681
#define sipName_send &sipStrings_QtDBus[3681]
#define sipNameNr_call 3686
#define sipName_call &sipStrings_QtDBus[3686]
#define sipNameNr_arg8 3691
#define sipName_arg8 &sipStrings_QtDBus[3691]
#define sipNameNr_arg7 3696
#define sipName_arg7 &sipStrings_QtDBus[3696]
#define sipNameNr_arg6 3701
#define sipName_arg6 &sipStrings_QtDBus[3701]
#define sipNameNr_arg5 3706
#define sipName_arg5 &sipStrings_QtDBus[3706]
#define sipNameNr_arg4 3711
#define sipName_arg4 &sipStrings_QtDBus[3711]
#define sipNameNr_arg3 3716
#define sipName_arg3 &sipStrings_QtDBus[3716]
#define sipNameNr_arg2 3721
#define sipName_arg2 &sipStrings_QtDBus[3721]
#define sipNameNr_arg1 3726
#define sipName_arg1 &sipStrings_QtDBus[3726]
#define sipNameNr_mode 3731
#define sipName_mode &sipStrings_QtDBus[3731]
#define sipNameNr_name 3736
#define sipName_name &sipStrings_QtDBus[3736]
#define sipNameNr_base 3741
#define sipName_base &sipStrings_QtDBus[3741]
#define sipNameNr_from 3746
#define sipName_from &sipStrings_QtDBus[3746]
#define sipNameNr_sort 3751
#define sipName_sort &sipStrings_QtDBus[3751]
#define sipNameNr_path 3756
#define sipName_path &sipStrings_QtDBus[3756]
#define sipNameNr_type 3761
#define sipName_type &sipStrings_QtDBus[3761]
#define sipNameNr_add 3766
#define sipName_add &sipStrings_QtDBus[3766]
#define sipNameNr_end 3682
#define sipName_end &sipStrings_QtDBus[3682]
#define sipNameNr_cs 3678
#define sipName_cs &sipStrings_QtDBus[3678]
#define sipNameNr_id 2926
#define sipName_id &sipStrings_QtDBus[2926]

#define sipMalloc                   sipAPI_QtDBus->api_malloc
#define sipFree                     sipAPI_QtDBus->api_free
#define sipBuildResult              sipAPI_QtDBus->api_build_result
#define sipCallMethod               sipAPI_QtDBus->api_call_method
#define sipCallProcedureMethod      sipAPI_QtDBus->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_QtDBus->api_call_error_handler
#define sipParseResultEx            sipAPI_QtDBus->api_parse_result_ex
#define sipParseResult              sipAPI_QtDBus->api_parse_result
#define sipParseArgs                sipAPI_QtDBus->api_parse_args
#define sipParseKwdArgs             sipAPI_QtDBus->api_parse_kwd_args
#define sipParsePair                sipAPI_QtDBus->api_parse_pair
#define sipCommonDtor               sipAPI_QtDBus->api_common_dtor
#define sipConvertFromSequenceIndex sipAPI_QtDBus->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_QtDBus->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_QtDBus->api_convert_to_void_ptr
#define sipAddException             sipAPI_QtDBus->api_add_exception
#define sipNoFunction               sipAPI_QtDBus->api_no_function
#define sipNoMethod                 sipAPI_QtDBus->api_no_method
#define sipAbstractMethod           sipAPI_QtDBus->api_abstract_method
#define sipBadClass                 sipAPI_QtDBus->api_bad_class
#define sipBadCatcherResult         sipAPI_QtDBus->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_QtDBus->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_QtDBus->api_bad_operator_arg
#define sipTrace                    sipAPI_QtDBus->api_trace
#define sipTransferBack             sipAPI_QtDBus->api_transfer_back
#define sipTransferTo               sipAPI_QtDBus->api_transfer_to
#define sipTransferBreak            sipAPI_QtDBus->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_QtDBus->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_QtDBus->api_wrapper_type
#define sipWrapperType_Type         sipAPI_QtDBus->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_QtDBus->api_voidptr_type
#define sipGetPyObject              sipAPI_QtDBus->api_get_pyobject
#define sipGetAddress               sipAPI_QtDBus->api_get_address
#define sipGetMixinAddress          sipAPI_QtDBus->api_get_mixin_address
#define sipGetCppPtr                sipAPI_QtDBus->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_QtDBus->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_QtDBus->api_is_py_method
#define sipCallHook                 sipAPI_QtDBus->api_call_hook
#define sipEndThread                sipAPI_QtDBus->api_end_thread
#define sipConnectRx                sipAPI_QtDBus->api_connect_rx
#define sipDisconnectRx             sipAPI_QtDBus->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_QtDBus->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_QtDBus->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_QtDBus->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_QtDBus->api_add_type_instance
#define sipFreeSipslot              sipAPI_QtDBus->api_free_sipslot
#define sipSameSlot                 sipAPI_QtDBus->api_same_slot
#define sipPySlotExtend             sipAPI_QtDBus->api_pyslot_extend
#define sipConvertRx                sipAPI_QtDBus->api_convert_rx
#define sipAddDelayedDtor           sipAPI_QtDBus->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_QtDBus->api_can_convert_to_type
#define sipConvertToType            sipAPI_QtDBus->api_convert_to_type
#define sipForceConvertToType       sipAPI_QtDBus->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_QtDBus->api_can_convert_to_enum
#define sipReleaseType              sipAPI_QtDBus->api_release_type
#define sipConvertFromType          sipAPI_QtDBus->api_convert_from_type
#define sipConvertFromNewType       sipAPI_QtDBus->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_QtDBus->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_QtDBus->api_convert_from_enum
#define sipGetState                 sipAPI_QtDBus->api_get_state
#define sipLong_AsUnsignedLong      sipAPI_QtDBus->api_long_as_unsigned_long
#define sipExportSymbol             sipAPI_QtDBus->api_export_symbol
#define sipImportSymbol             sipAPI_QtDBus->api_import_symbol
#define sipFindType                 sipAPI_QtDBus->api_find_type
#define sipFindNamedEnum            sipAPI_QtDBus->api_find_named_enum
#define sipBytes_AsChar             sipAPI_QtDBus->api_bytes_as_char
#define sipBytes_AsString           sipAPI_QtDBus->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_QtDBus->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_QtDBus->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_QtDBus->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_QtDBus->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_QtDBus->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_QtDBus->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_QtDBus->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_QtDBus->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_QtDBus->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_QtDBus->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_QtDBus->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_QtDBus->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_QtDBus->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_QtDBus->api_save_slot
#define sipClearAnySlotReference    sipAPI_QtDBus->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_QtDBus->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_QtDBus->api_deprecated
#define sipGetReference             sipAPI_QtDBus->api_get_reference
#define sipKeepReference            sipAPI_QtDBus->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_QtDBus->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_QtDBus->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_QtDBus->api_type_from_py_type_object
#define sipTypeScope                sipAPI_QtDBus->api_type_scope
#define sipResolveTypedef           sipAPI_QtDBus->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_QtDBus->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_QtDBus->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_QtDBus->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_QtDBus->api_enable_autoconversion
#define sipInitMixin                sipAPI_QtDBus->api_init_mixin
#define sipExportModule             sipAPI_QtDBus->api_export_module
#define sipInitModule               sipAPI_QtDBus->api_init_module
#define sipGetInterpreter           sipAPI_QtDBus->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_QtDBus->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_QtDBus->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_QtDBus->api_get_type_user_data
#define sipPyTypeDict               sipAPI_QtDBus->api_py_type_dict
#define sipPyTypeName               sipAPI_QtDBus->api_py_type_name
#define sipGetCFunction             sipAPI_QtDBus->api_get_c_function
#define sipGetMethod                sipAPI_QtDBus->api_get_method
#define sipFromMethod               sipAPI_QtDBus->api_from_method
#define sipGetDate                  sipAPI_QtDBus->api_get_date
#define sipFromDate                 sipAPI_QtDBus->api_from_date
#define sipGetDateTime              sipAPI_QtDBus->api_get_datetime
#define sipFromDateTime             sipAPI_QtDBus->api_from_datetime
#define sipGetTime                  sipAPI_QtDBus->api_get_time
#define sipFromTime                 sipAPI_QtDBus->api_from_time
#define sipIsUserType               sipAPI_QtDBus->api_is_user_type
#define sipGetFrame                 sipAPI_QtDBus->api_get_frame
#define sipCheckPluginForType       sipAPI_QtDBus->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_QtDBus->api_unicode_new
#define sipUnicodeWrite             sipAPI_QtDBus->api_unicode_write
#define sipUnicodeData              sipAPI_QtDBus->api_unicode_data
#define sipGetBufferInfo            sipAPI_QtDBus->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_QtDBus->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_QtDBus->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_QtDBus->api_is_derived_class
#define sipGetUserObject            sipAPI_QtDBus->api_get_user_object
#define sipSetUserObject            sipAPI_QtDBus->api_set_user_object

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_QtDBus->api_map_string_to_class
#define sipMapIntToClass            sipAPI_QtDBus->api_map_int_to_class
#define sipFindClass                sipAPI_QtDBus->api_find_class
#define sipFindMappedType           sipAPI_QtDBus->api_find_mapped_type
#define sipConvertToArray           sipAPI_QtDBus->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_QtDBus->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_QtDBus->api_enable_gc
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_QtDBus->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_QtDBus[];

#define sipType_QDBusAbstractAdaptor sipExportedTypes_QtDBus[2]
#define sipClass_QDBusAbstractAdaptor sipExportedTypes_QtDBus[2]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusAbstractAdaptor;

#define sipType_QDBusAbstractInterface sipExportedTypes_QtDBus[3]
#define sipClass_QDBusAbstractInterface sipExportedTypes_QtDBus[3]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusAbstractInterface;

#define sipType_QDBusArgument sipExportedTypes_QtDBus[4]
#define sipClass_QDBusArgument sipExportedTypes_QtDBus[4]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusArgument;

#define sipType_QDBus sipExportedTypes_QtDBus[0]
#define sipClass_QDBus sipExportedTypes_QtDBus[0]->u.td_wrapper_type

#define sipType_QDBus_CallMode sipExportedTypes_QtDBus[1]
#define sipEnum_QDBus_CallMode sipExportedTypes_QtDBus[1]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBus;

#define sipType_QDBusConnection sipExportedTypes_QtDBus[5]
#define sipClass_QDBusConnection sipExportedTypes_QtDBus[5]->u.td_wrapper_type

#define sipType_QDBusConnection_ConnectionCapability sipExportedTypes_QtDBus[8]
#define sipEnum_QDBusConnection_ConnectionCapability sipExportedTypes_QtDBus[8]->u.td_py_type

#define sipType_QDBusConnection_UnregisterMode sipExportedTypes_QtDBus[11]
#define sipEnum_QDBusConnection_UnregisterMode sipExportedTypes_QtDBus[11]->u.td_py_type

#define sipType_QDBusConnection_RegisterOption sipExportedTypes_QtDBus[9]
#define sipEnum_QDBusConnection_RegisterOption sipExportedTypes_QtDBus[9]->u.td_py_type

#define sipType_QDBusConnection_BusType sipExportedTypes_QtDBus[6]
#define sipEnum_QDBusConnection_BusType sipExportedTypes_QtDBus[6]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusConnection;

#define sipType_QDBusConnection_RegisterOptions sipExportedTypes_QtDBus[10]
#define sipClass_QDBusConnection_RegisterOptions sipExportedTypes_QtDBus[10]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusConnection_RegisterOptions;

#define sipType_QDBusConnection_ConnectionCapabilities sipExportedTypes_QtDBus[7]
#define sipClass_QDBusConnection_ConnectionCapabilities sipExportedTypes_QtDBus[7]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusConnection_ConnectionCapabilities;

#define sipType_QDBusConnectionInterface sipExportedTypes_QtDBus[12]
#define sipClass_QDBusConnectionInterface sipExportedTypes_QtDBus[12]->u.td_wrapper_type

#define sipType_QDBusConnectionInterface_RegisterServiceReply sipExportedTypes_QtDBus[13]
#define sipEnum_QDBusConnectionInterface_RegisterServiceReply sipExportedTypes_QtDBus[13]->u.td_py_type

#define sipType_QDBusConnectionInterface_ServiceReplacementOptions sipExportedTypes_QtDBus[15]
#define sipEnum_QDBusConnectionInterface_ServiceReplacementOptions sipExportedTypes_QtDBus[15]->u.td_py_type

#define sipType_QDBusConnectionInterface_ServiceQueueOptions sipExportedTypes_QtDBus[14]
#define sipEnum_QDBusConnectionInterface_ServiceQueueOptions sipExportedTypes_QtDBus[14]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusConnectionInterface;

#define sipType_QDBusError sipExportedTypes_QtDBus[16]
#define sipClass_QDBusError sipExportedTypes_QtDBus[16]->u.td_wrapper_type

#define sipType_QDBusError_ErrorType sipExportedTypes_QtDBus[17]
#define sipEnum_QDBusError_ErrorType sipExportedTypes_QtDBus[17]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusError;

#define sipType_QDBusObjectPath sipExportedTypes_QtDBus[21]
#define sipClass_QDBusObjectPath sipExportedTypes_QtDBus[21]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusObjectPath;

#define sipType_QDBusSignature sipExportedTypes_QtDBus[33]
#define sipClass_QDBusSignature sipExportedTypes_QtDBus[33]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusSignature;

#define sipType_QDBusVariant sipExportedTypes_QtDBus[35]
#define sipClass_QDBusVariant sipExportedTypes_QtDBus[35]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusVariant;

#define sipType_QDBusInterface sipExportedTypes_QtDBus[18]
#define sipClass_QDBusInterface sipExportedTypes_QtDBus[18]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusInterface;

#define sipType_QDBusMessage sipExportedTypes_QtDBus[19]
#define sipClass_QDBusMessage sipExportedTypes_QtDBus[19]->u.td_wrapper_type

#define sipType_QDBusMessage_MessageType sipExportedTypes_QtDBus[20]
#define sipEnum_QDBusMessage_MessageType sipExportedTypes_QtDBus[20]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusMessage;

#define sipType_QDBusPendingCall sipExportedTypes_QtDBus[22]
#define sipClass_QDBusPendingCall sipExportedTypes_QtDBus[22]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusPendingCall;

#define sipType_QDBusPendingCallWatcher sipExportedTypes_QtDBus[23]
#define sipClass_QDBusPendingCallWatcher sipExportedTypes_QtDBus[23]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusPendingCallWatcher;

#define sipType_QDBusServiceWatcher sipExportedTypes_QtDBus[30]
#define sipClass_QDBusServiceWatcher sipExportedTypes_QtDBus[30]->u.td_wrapper_type

#define sipType_QDBusServiceWatcher_WatchModeFlag sipExportedTypes_QtDBus[32]
#define sipEnum_QDBusServiceWatcher_WatchModeFlag sipExportedTypes_QtDBus[32]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusServiceWatcher;

#define sipType_QDBusServiceWatcher_WatchMode sipExportedTypes_QtDBus[31]
#define sipClass_QDBusServiceWatcher_WatchMode sipExportedTypes_QtDBus[31]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusServiceWatcher_WatchMode;

#define sipType_QDBusUnixFileDescriptor sipExportedTypes_QtDBus[34]
#define sipClass_QDBusUnixFileDescriptor sipExportedTypes_QtDBus[34]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtDBus_QDBusUnixFileDescriptor;

#define sipType_QPyDBusPendingReply sipExportedTypes_QtDBus[36]
#define sipClass_QPyDBusPendingReply sipExportedTypes_QtDBus[36]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtDBus_QPyDBusPendingReply;

#define sipType_QPyDBusReply sipExportedTypes_QtDBus[37]
#define sipClass_QPyDBusReply sipExportedTypes_QtDBus[37]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtDBus_QPyDBusReply;

#define sipType_QDBusReply_0100QString sipExportedTypes_QtDBus[25]

extern sipMappedTypeDef sipTypeDef_QtDBus_QDBusReply_0100QString;

#define sipType_QDBusReply_0100QStringList sipExportedTypes_QtDBus[26]

extern sipMappedTypeDef sipTypeDef_QtDBus_QDBusReply_0100QStringList;

#define sipType_QDBusReply_0100QDBusConnectionInterface_RegisterServiceReply sipExportedTypes_QtDBus[24]

extern sipMappedTypeDef sipTypeDef_QtDBus_QDBusReply_0100QDBusConnectionInterface_RegisterServiceReply;

#define sipType_QDBusReply_1900 sipExportedTypes_QtDBus[28]

extern sipMappedTypeDef sipTypeDef_QtDBus_QDBusReply_1900;

#define sipType_QDBusReply_2600 sipExportedTypes_QtDBus[27]

extern sipMappedTypeDef sipTypeDef_QtDBus_QDBusReply_2600;

#define sipType_QDBusReply_0400 sipExportedTypes_QtDBus[29]

extern sipMappedTypeDef sipTypeDef_QtDBus_QDBusReply_0400;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_QtDBus;
extern sipExportedModuleDef sipModuleAPI_QtDBus;
extern sipTypeDef *sipExportedTypes_QtDBus[];

#define sipType_QObject sipImportedTypes_QtDBus_QtCore[4].it_td
#define sipClass_QObject sipImportedTypes_QtDBus_QtCore[4].it_td->u.td_wrapper_type

#define sipType_QByteArray sipImportedTypes_QtDBus_QtCore[0].it_td
#define sipClass_QByteArray sipImportedTypes_QtDBus_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_QtDBus_QtCore[2].it_td
#define sipClass_QEvent sipImportedTypes_QtDBus_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_QtDBus_QtCore[7].it_td
#define sipClass_QTimerEvent sipImportedTypes_QtDBus_QtCore[7].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_QtDBus_QtCore[1].it_td
#define sipClass_QChildEvent sipImportedTypes_QtDBus_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QVariant sipImportedTypes_QtDBus_QtCore[8].it_td
#define sipClass_QVariant sipImportedTypes_QtDBus_QtCore[8].it_td->u.td_wrapper_type

#define sipType_QList_0100QVariant sipImportedTypes_QtDBus_QtCore[3].it_td

#define sipType_QStringList sipImportedTypes_QtDBus_QtCore[6].it_td

#define sipType_QString sipImportedTypes_QtDBus_QtCore[5].it_td
extern sipImportedTypeDef sipImportedTypes_QtDBus_QtCore[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_QtDBus_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_QtDBus_qt_metacall;

typedef int (*sip_qt_metacast_func)(sipSimpleWrapper *, sipTypeDef *, const char *);
extern sip_qt_metacast_func sip_QtDBus_qt_metacast;
#line 251 "/home/thais/Faculdade/TCC/NEW/PyQt4_gpl_x11-4.12/sip/QtDBus/qdbusabstractinterface.sip"
// Imports from QtCore.
typedef PyObject *(*pyqt4_qtdbus_from_qvariant_by_type_t)(QVariant &, PyObject *);
extern pyqt4_qtdbus_from_qvariant_by_type_t pyqt4_qtdbus_from_qvariant_by_type;

typedef sipErrorState (*pyqt4_qtdbus_get_pyqtslot_parts_t)(PyObject *, QObject **, QByteArray &);
extern pyqt4_qtdbus_get_pyqtslot_parts_t pyqt4_qtdbus_get_pyqtslot_parts;

typedef const char *(*pyqt4_qtdbus_get_slot_t)(PyObject *);
extern pyqt4_qtdbus_get_slot_t pyqt4_qtdbus_get_slot;

#include <qpydbus_api.h>
#line 1004 "/home/thais/Faculdade/TCC/NEW/PyQt4_gpl_x11-4.12/QtDBus/sipAPIQtDBus.h"

#endif
